begin;
create extension if not exists pgtap with schema extensions;
select extensions.no_plan();
insert into auth.users(id,email,role,aud,email_confirmed_at,raw_user_meta_data)
select md5('b08-policy-user-'||n)::uuid,'b08-policy-'||n||'@example.test','authenticated','authenticated',now(),
 '{"b08_terms":"fictional-terms-v1","b08_privacy":"fictional-privacy-v1"}'::jsonb from generate_series(1,3)n;
select extensions.is((select count(*) from private.account_policy_acceptances where user_id=md5('b08-policy-user-2')::uuid),0::bigint,'user metadata cannot forge policy acceptance');
update auth.users set raw_app_meta_data='{"b08_terms":"fictional-terms-v1","b08_privacy":"fictional-privacy-v1"}'::jsonb where id=md5('b08-policy-user-1')::uuid;
select extensions.is((select count(*) from private.account_policy_acceptances where user_id=md5('b08-policy-user-1')::uuid),1::bigint,'server-owned signup policy receipt recorded');
select extensions.ok(not has_table_privilege('authenticated','private.account_policy_acceptances','SELECT'),'no account-wide consent listing');
select extensions.ok(not has_table_privilege('authenticated','private.account_session_activity','UPDATE'),'browser cannot forge activity timestamps');
select extensions.ok(not has_function_privilege('anon','public.preview_my_invitation(uuid)','EXECUTE'),'no anonymous recipient preview');
select extensions.ok(not has_function_privilege('service_role','public.preview_my_invitation(uuid)','EXECUTE'),'preview is not a service lookup');
select extensions.ok(not has_function_privilege('authenticated','public.admit_local_account_mail(text,text,uuid,text)','EXECUTE'),'ordinary user cannot call mail admission');
select extensions.ok(has_function_privilege('service_role','public.admit_local_account_mail(text,text,uuid,text)','EXECUTE'),'gated server may call mail admission');
select extensions.ok(not has_function_privilege('anon','public.record_account_activity()','EXECUTE'),'anonymous activity denied');
select extensions.ok(not has_function_privilege('service_role','public.record_account_activity()','EXECUTE'),'activity is bound to genuine user session');
insert into public.organizations(id,name,slug)values(md5('b08-policy-org')::uuid,'B08 policy fixture','b08-policy-fixture');
insert into public.organization_memberships(organization_id,user_id,role,status,joined_at)values(md5('b08-policy-org')::uuid,md5('b08-policy-user-1')::uuid,'owner','active',now());
insert into public.organization_invitations(id,organization_id,email,expires_at,created_by)
values(md5('b08-policy-invite')::uuid,md5('b08-policy-org')::uuid,'b08-policy-2@example.test',now()+interval '1 day',md5('b08-policy-user-1')::uuid);
select extensions.is(public.admit_local_account_mail('signup','b08-policy-2@example.test',md5('b08-policy-invite')::uuid,repeat('a',64))->>'allowed','true','eligible signup mail admission');
select extensions.is(public.admit_local_account_mail('signup','wrong@example.test',md5('b08-policy-invite')::uuid,repeat('a',64))->>'allowed','false','wrong-email signup unavailable');
select extensions.throws_ok($$select public.admit_local_account_mail(null,'a@example.test',null,repeat('b',64))$$,'PT400','Request unavailable','null action rejected');
set local role authenticated;
select set_config('request.jwt.claims',json_build_object('sub',md5('b08-policy-user-3')::uuid,'role','authenticated')::text,true);
select extensions.is(public.preview_my_invitation(md5('b08-policy-invite')::uuid),null::jsonb,'wrong verified account cannot preview');
select set_config('request.jwt.claims',json_build_object('sub',md5('b08-policy-user-2')::uuid,'role','authenticated')::text,true);
select extensions.is(public.preview_my_invitation(md5('b08-policy-invite')::uuid)->>'organizationName','B08 policy fixture','matching verified recipient sees minimal preview');
select extensions.is((select count(*) from jsonb_object_keys(public.preview_my_invitation(md5('b08-policy-invite')::uuid))),6::bigint,'preview has only approved fields plus invitation identity');
set local role postgres;
update auth.users set email_confirmed_at=null where id=md5('b08-policy-user-2')::uuid;
set local role authenticated;
select extensions.is(public.preview_my_invitation(md5('b08-policy-invite')::uuid),null::jsonb,'unverified email denies preview');
set local role postgres;
update auth.users set email_confirmed_at=now() where id=md5('b08-policy-user-2')::uuid;
insert into auth.sessions(id,user_id,created_at,updated_at)values(md5('b08-policy-session')::uuid,md5('b08-policy-user-2')::uuid,now(),now());
set local role authenticated;
select set_config('request.jwt.claims',json_build_object('sub',md5('b08-policy-user-2')::uuid,'role','authenticated','session_id',md5('b08-policy-session')::uuid,'exp',extract(epoch from now()+interval '1 hour')::bigint)::text,true);
select extensions.is(public.get_account_policy_status()->>'accepted','false','new actor has no acceptance');
select extensions.throws_ok($$select public.accept_account_policies('stale','fictional-privacy-v1')$$,'PT409','Review current policies','stale policy review rejected');
select extensions.is(public.accept_account_policies('fictional-terms-v1','fictional-privacy-v1')->>'accepted','true','current policy review accepted');
select extensions.lives_ok('select public.record_account_activity()','active session records server-time activity');
set local role postgres;
update auth.sessions set created_at=now()-interval '15 hours' where id=md5('b08-policy-session')::uuid;
set local role authenticated;
select extensions.lives_ok('select public.get_account_session_deadline()','continued activity has no fixed absolute limit');
set local role postgres;
update private.account_session_activity set last_activity_at=now()-interval '61 minutes' where session_id=md5('b08-policy-session')::uuid;
set local role authenticated;
select extensions.throws_ok('select public.record_account_activity()','PT401','Active session required','expired session cannot revive activity');
set local role postgres;
update auth.users set encrypted_password='fictional-changed-value' where id=md5('b08-policy-user-2')::uuid;
select extensions.ok((select not_after<=clock_timestamp() from auth.sessions where id=md5('b08-policy-session')::uuid),'password change expires existing session in same transaction');
select extensions.is((select count(*) from public.audit_events where actor_user_id=md5('b08-policy-user-2')::uuid and action='account.password.sessions_expired'),1::bigint,'password-session invalidation audited without secrets');
update auth.sessions set not_after=null where id=md5('b08-policy-session')::uuid;
update private.account_session_activity set last_activity_at=now() where session_id=md5('b08-policy-session')::uuid;
update private.account_policy_versions set enforce_acceptance=true,terms_version='fictional-material-v2';
select set_config('request.path','/rpc/preview_my_invitation',true);
set local role authenticated;
select extensions.throws_ok('select public.require_active_schedule_session()','PT428','Review current account policies','server admission requires current material terms');
select set_config('request.path','/rpc/accept_account_policies',true);
select extensions.lives_ok($$select public.accept_account_policies('fictional-material-v2','fictional-privacy-v1')$$,'policy review remains available through admission gate');
select set_config('request.path','/rpc/preview_my_invitation',true);
select extensions.lives_ok('select public.require_active_schedule_session()','accepted material terms restore admission');
select extensions.ok(not has_function_privilege('authenticated','public.get_local_account_policy_configuration()','EXECUTE'),'ordinary user cannot inspect rollout configuration');
select * from extensions.finish();
rollback;
