begin;
create extension if not exists pgtap with schema extensions;
select extensions.no_plan();
insert into auth.users(id,email,role,aud,email_confirmed_at)
select md5('receipt-user-'||n)::uuid,'receipt-'||n||'@example.test','authenticated','authenticated',now() from generate_series(1,3) n;
insert into public.organizations(id,name,slug) values(md5('receipt-org')::uuid,'Receipt fixture','receipt-fixture');
insert into public.organization_memberships(organization_id,user_id,role,status,joined_at)
values(md5('receipt-org')::uuid,md5('receipt-user-1')::uuid,'owner','active',now());
insert into public.productions(id,organization_id,name,slug) values(md5('receipt-prod')::uuid,md5('receipt-org')::uuid,'Receipt production','receipt');
insert into public.organization_invitations(id,organization_id,email,production_id,production_role,expires_at,created_by)
values(md5('receipt-invite')::uuid,md5('receipt-org')::uuid,' Receipt-2@example.test ',md5('receipt-prod')::uuid,'viewer',now()+interval '1 day',md5('receipt-user-1')::uuid);
select extensions.ok(not has_function_privilege('anon','public.get_my_invitation_acceptance(uuid)','EXECUTE'),'anonymous cannot call receipt RPC');
select extensions.ok(not has_function_privilege('service_role','public.get_my_invitation_acceptance(uuid)','EXECUTE'),'receipt does not create service-role lookup');
select extensions.ok(has_function_privilege('authenticated','public.get_my_invitation_acceptance(uuid)','EXECUTE'),'authenticated recipient can call scoped receipt RPC');
select extensions.ok((select prosecdef and provolatile='s' and proconfig=array['search_path=""'] from pg_proc where oid='public.get_my_invitation_acceptance(uuid)'::regprocedure),'receipt is stable with fixed empty search path');
set local role authenticated;
select set_config('request.jwt.claims',json_build_object('sub',md5('receipt-user-3')::uuid,'role','authenticated','aal','aal2')::text,true);
select extensions.is(public.get_my_invitation_acceptance(md5('receipt-invite')::uuid),null::jsonb,'wrong account cannot inspect pending invitation');
select extensions.throws_ok($$select public.accept_organization_invitation(md5('receipt-invite')::uuid)$$,'P0001','invitation unavailable','wrong account cannot accept');
select set_config('request.jwt.claims',json_build_object('sub',md5('receipt-user-2')::uuid,'role','authenticated','aal','aal2')::text,true);
select extensions.is(public.get_my_invitation_acceptance(md5('receipt-invite')::uuid),null::jsonb,'matching pending invitation has no acceptance receipt');
select extensions.is(public.accept_organization_invitation(md5('receipt-invite')::uuid),md5('receipt-org')::uuid,'verified matching recipient accepts existing RPC');
select extensions.is(public.get_my_invitation_acceptance(md5('receipt-invite')::uuid)->>'organizationId',md5('receipt-org')::uuid::text,'own accepted receipt confirms organization');
select extensions.is((select count(*) from jsonb_object_keys(public.get_my_invitation_acceptance(md5('receipt-invite')::uuid))),3::bigint,'receipt exposes only invitation, organization and acceptance time');
select extensions.is((select count(*) from public.organization_invitations where id=md5('receipt-invite')::uuid),0::bigint,'recipient still cannot list admin-only invitation row');
select extensions.throws_ok($$select public.accept_organization_invitation(md5('receipt-invite')::uuid)$$,'P0001','invitation unavailable','original single-use RPC still rejects replay');
select set_config('request.jwt.claims',json_build_object('sub',md5('receipt-user-1')::uuid,'role','authenticated','aal','aal2')::text,true);
select extensions.is(public.get_my_invitation_acceptance(md5('receipt-invite')::uuid),null::jsonb,'even owner cannot use recipient receipt for another actor');
select extensions.is((select count(*) from public.audit_events where resource_id=md5('receipt-invite')::uuid and action='organization.invitation.accepted'),1::bigint,'replay and receipt add no duplicate audit');
set local role postgres;
update auth.users set email_confirmed_at=null where id=md5('receipt-user-2')::uuid;
set local role authenticated;
select set_config('request.jwt.claims',json_build_object('sub',md5('receipt-user-2')::uuid,'role','authenticated','aal','aal2')::text,true);
select extensions.is(public.get_my_invitation_acceptance(md5('receipt-invite')::uuid),null::jsonb,'unverified current email hides receipt');
set local role postgres;
update auth.users set email_confirmed_at=now(),email='changed-receipt@example.test' where id=md5('receipt-user-2')::uuid;
set local role authenticated;
select set_config('request.jwt.claims',json_build_object('sub',md5('receipt-user-2')::uuid,'role','authenticated','aal','aal2')::text,true);
select extensions.is(public.get_my_invitation_acceptance(md5('receipt-invite')::uuid),null::jsonb,'changed current email hides receipt');
set local role postgres;
update auth.users set email='receipt-2@example.test' where id=md5('receipt-user-2')::uuid;
update public.organization_memberships set status='suspended' where user_id=md5('receipt-user-2')::uuid;
set local role authenticated;
select set_config('request.jwt.claims',json_build_object('sub',md5('receipt-user-2')::uuid,'role','authenticated','aal','aal2')::text,true);
select extensions.is(public.get_my_invitation_acceptance(md5('receipt-invite')::uuid),null::jsonb,'suspended organization membership hides receipt');
set local role postgres;
update public.organization_memberships set status='active' where user_id=md5('receipt-user-2')::uuid;
update public.production_memberships set status='suspended' where user_id=md5('receipt-user-2')::uuid;
set local role authenticated;
select set_config('request.jwt.claims',json_build_object('sub',md5('receipt-user-2')::uuid,'role','authenticated','aal','aal2')::text,true);
select extensions.is(public.get_my_invitation_acceptance(md5('receipt-invite')::uuid),null::jsonb,'suspended production membership hides receipt');
set local role postgres;
update public.production_memberships set status='active' where user_id=md5('receipt-user-2')::uuid;
select set_config('request.jwt.claims',json_build_object('sub',md5('receipt-user-1')::uuid,'role','authenticated','aal','aal2')::text,true);
update public.productions set deleted_at=now() where id=md5('receipt-prod')::uuid;
set local role authenticated;
select set_config('request.jwt.claims',json_build_object('sub',md5('receipt-user-2')::uuid,'role','authenticated','aal','aal2')::text,true);
select extensions.is(public.get_my_invitation_acceptance(md5('receipt-invite')::uuid),null::jsonb,'deleted production hides receipt');
set local role postgres;
select set_config('request.jwt.claims',json_build_object('sub',md5('receipt-user-1')::uuid,'role','authenticated','aal','aal2')::text,true);
update public.productions set deleted_at=null where id=md5('receipt-prod')::uuid;
-- Legacy deleted-parent fixture only; this transaction rolls back. Current product deletion uses the B10 workflow.
alter table public.organizations disable trigger a_organization_writable;
update public.organizations set deleted_at=now() where id=md5('receipt-org')::uuid;
alter table public.organizations enable trigger a_organization_writable;
set local role authenticated;
select set_config('request.jwt.claims',json_build_object('sub',md5('receipt-user-2')::uuid,'role','authenticated','aal','aal2')::text,true);
select extensions.is(public.get_my_invitation_acceptance(md5('receipt-invite')::uuid),null::jsonb,'deleted organization hides receipt');
set local role postgres;
-- Legacy deleted-parent fixture only; this transaction rolls back. Current product deletion uses the B10 workflow.
alter table public.organizations disable trigger a_organization_writable;
update public.organizations set deleted_at=null where id=md5('receipt-org')::uuid;
alter table public.organizations enable trigger a_organization_writable;
set local role authenticated;
select set_config('request.jwt.claims',json_build_object('sub',md5('receipt-user-2')::uuid,'role','authenticated','aal','aal2')::text,true);
select extensions.is(public.get_my_invitation_acceptance(md5('receipt-invite')::uuid)->>'invitationId',md5('receipt-invite')::uuid::text,'active own receipt is recoverable without mutation');
select extensions.is(public.get_my_invitation_acceptance(md5('receipt-missing')::uuid),null::jsonb,'missing invitation reveals no details');
select * from extensions.finish();
rollback;
