begin;
create extension if not exists pgtap with schema extensions;
select plan(10);
select ok(not has_schema_privilege('authenticated','private','USAGE'), 'session wrappers do not expose the private schema');
select ok(not has_table_privilege('authenticated','auth.sessions','SELECT'), 'session table is not exposed to authenticated clients');
select ok(not has_function_privilege('anon','public.session_list_schedules(uuid,integer)','EXECUTE'), 'anonymous listing is forbidden');
select ok(not has_function_privilege('anon','public.require_active_schedule_session()','EXECUTE'), 'anonymous session helper is forbidden');
select ok(not has_function_privilege('service_role','public.session_update_schedule_document(uuid,bigint,jsonb,integer)','EXECUTE'), 'service-role session write is forbidden');
select ok(has_function_privilege('authenticated','public.session_read_schedule(uuid)','EXECUTE'), 'authenticated role can invoke session read');
set local role authenticated;
select set_config('request.jwt.claims','{}',true);
select throws_ok('select public.session_list_schedules()', 'PT401', 'Active session required', 'missing identity/session is rejected');
select set_config('request.jwt.claims','{"sub":"aaaaaaaa-0000-4000-8000-000000000001","session_id":"bad","exp":9999999999}',true);
select throws_ok('select public.require_active_schedule_session()', 'PT401', 'Active session required', 'malformed session ID is bounded');
select set_config('request.jwt.claims','{"sub":"aaaaaaaa-0000-4000-8000-000000000001","session_id":"aaaaaaaa-0000-4000-8000-000000000002","exp":1}',true);
select throws_ok('select public.require_active_schedule_session()', 'PT401', 'Active session required', 'expired JWT claim is rejected');
select set_config('request.jwt.claims','{"sub":"aaaaaaaa-0000-4000-8000-000000000001","session_id":"aaaaaaaa-0000-4000-8000-000000000002","exp":9999999999}',true);
select throws_ok('select public.session_list_schedules()', 'PT401', 'Active session required', 'nonexistent/revoked session is rejected');
reset role;
select * from finish();
rollback;
