'use client';
import { useRef, useState } from 'react';
import { useLocalWorkspace, useWorkspacePanelState } from './LocalWorkspaceContext';
import styles from '@/app/local-workspace/workspace.module.css';
const actions={discover:'Find productions',read:'Read schedules',history:'Read history',edit:'Edit and save',create:'Create and copy',organize:'Rename, arrange and archive',trash:'Trash and recover',export:'Export and print',transfer:'Move schedules',permissions:'Manage permissions'};
type Action=keyof typeof actions;
type Rule={id:string;organization_id:string;production_id:string|null;schedule_id:string|null;subject_role:string|null;subject_user_id:string|null;denied_actions:Action[];authority:string;revision:number};
type Directory={productions:{id:string;name:string}[];schedules:{id:string;name:string;production:string}[];members:{id:string;name:string;role:string}[]};
export default function LocalSchedulePermissions(){
 const w=useLocalWorkspace()!,[directory,setDirectory]=useState<Directory|null>(null),[rules,setRules]=useState<Rule[]>([]),[effective,setEffective]=useState<Record<string,boolean>>({});
 const [production,setProduction]=useState(''),[schedule,setSchedule]=useState(''),[subject,setSubject]=useState('role:editor'),[denied,setDenied]=useState<Action[]>([]),[selected,setSelected]=useState<Rule|null>(null);
 const [busy,setBusy]=useState(false),[dirty,setDirty]=useState(false),[message,setMessage]=useState('Standard access applies immediately. Restrictions are optional.'),[member,setMember]=useState(''),[role,setRole]=useState('organizer');
 const requestId=useRef<string|null>(null),busyRef=useRef(false),latest=useRef(w);latest.current=w;
 useWorkspacePanelState(dirty,busy);
 const ready=!!w.session&&!w.authNeeded&&w.active,owner=w.organization?.role==='owner';
 async function rpc(name:string,args:Record<string,unknown>){const token=w.session?.access_token;if(!token)throw Error('Sign in again. Your changes are retained.');const r=await w.client.rpc(name,args).setHeader('Authorization',`Bearer ${token}`);if(r.error)throw Error(r.error.code==='PT409'?'Permissions changed. Refresh and review before saving.':r.status===401?'Sign in again. Your changes are retained.':'This permission action is unavailable. Your changes are retained.');if(latest.current.session?.access_token!==token||!latest.current.active)throw Error('Workspace changed. Refresh before continuing.');return r.data;}
 async function run(action:()=>Promise<void>){if(!ready||busyRef.current)return;busyRef.current=true;setBusy(true);try{await action();}catch(e){setMessage(e instanceof Error?e.message:'Permissions could not be loaded.');}finally{busyRef.current=false;setBusy(false);}}
 async function load(prod=production,sched=schedule){const result=await rpc('read_schedule_permissions',{target_organization_id:w.organization!.id,target_production_id:prod||null,target_schedule_id:sched||null});setRules(result.restrictions);setEffective(result.effective);}
 function reset(){setSelected(null);setDenied([]);requestId.current=null;setDirty(false);}
 function choose(rule:Rule){setSelected(rule);setSubject(rule.subject_user_id?'user:'+rule.subject_user_id:'role:'+rule.subject_role);setDenied(rule.denied_actions);setDirty(false);requestId.current=rule.id;}
 const editable=!selected||(selected.production_id===(production||null)&&selected.schedule_id===(schedule||null)&&(owner||selected.authority!=='owner'));
 return <details className={styles.shell} onToggle={e=>{if(e.currentTarget.open&&!directory)void run(async()=>{setDirectory(await rpc('schedule_permission_directory',{target_organization_id:w.organization!.id}));await load();});}}>
  <summary>Settings · Permissions</summary><p>Inherited restrictions always apply. These controls remove Standard access; they never grant content access.</p><p role="status">{message}</p>
  {directory&&<><div className={styles.directory}><label>Production<select disabled={!ready||busy||dirty} value={production} onChange={e=>{const p=e.target.value;setProduction(p);setSchedule('');reset();void run(()=>load(p,''));}}><option value="">Organization</option>{directory.productions.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Schedule<select disabled={!ready||busy||dirty||!production} value={schedule} onChange={e=>{const s=e.target.value;setSchedule(s);reset();void run(()=>load(production,s));}}><option value="">All schedules in this scope</option>{directory.schedules.filter(s=>s.production===production).map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label></div>
   <p>Your effective access: {Object.entries(actions).filter(([key])=>effective[key]).map(([,label])=>label).join(', ')||'No scheduling actions'}.</p>
   <ul>{rules.map(rule=><li key={rule.id}><button disabled={!ready||busy||dirty} onClick={()=>choose(rule)}>{rule.subject_role==='owner'?'Organization Super Admin':rule.subject_role||directory.members.find(m=>m.id===rule.subject_user_id)?.name||'Organization member'} · {rule.production_id===(production||null)&&rule.schedule_id===(schedule||null)?'Explicit':'Inherited'} · {rule.denied_actions.map(a=>actions[a]).join(', ')}</button>{rule.authority==='owner'?' · Set by Super Admin':''}</li>)}</ul>
   <form onSubmit={e=>{e.preventDefault();void run(async()=>{requestId.current??=crypto.randomUUID();await rpc('set_schedule_restriction',{target_id:requestId.current,target_organization_id:w.organization!.id,target_production_id:production||null,target_schedule_id:schedule||null,subject_role:subject.startsWith('role:')?subject.slice(5):null,subject_user_id:subject.startsWith('user:')?subject.slice(5):null,denied_actions:denied,expected_revision:selected?.revision??0});reset();await load();setMessage('Permissions saved. Inherited restrictions still apply.');});}}>
    <fieldset disabled={!ready||busy||!editable}><legend>{selected?'Review restriction':'Add restriction'}</legend><label>Applies to<select disabled={!!selected} value={subject} onChange={e=>{setSubject(e.target.value);setDirty(true);}}>{(owner?['everyone','owner','admin','organizer','editor','viewer']:['organizer','editor','viewer']).map(x=><option key={x} value={'role:'+x}>{x==='owner'?'Organization Super Admin':x==='everyone'?'Everyone':x[0].toUpperCase()+x.slice(1)}</option>)}{directory.members.filter(m=>owner||m.role==='member').map(m=><option key={m.id} value={'user:'+m.id}>{m.name}</option>)}</select></label>
    <details open><summary>Restricted actions</summary>{Object.entries(actions).map(([key,label])=><label key={key} style={{display:'flex',alignItems:'center',gap:8,margin:'8px 0'}}><input type="checkbox" checked={denied.includes(key as Action)} onChange={e=>{setDenied(v=>e.target.checked?[...v,key as Action]:v.filter(a=>a!==key));setDirty(true);}}/>{label}</label>)}</details>
    <button disabled={!dirty||(!selected&&!denied.length)}>Save permissions</button></fieldset>
    {!editable&&<p>This restriction is inherited or set by higher authority. It cannot be changed here.</p>}
   </form><button disabled={busy} onClick={reset}>{dirty?'Discard permission draft':'New restriction'}</button><button disabled={!ready||busy||dirty} onClick={()=>void run(()=>load())}>Refresh permissions</button>
   {production&&<details><summary>Production roles</summary><form onSubmit={e=>{e.preventDefault();void run(async()=>{await rpc('assign_production_role',{target_production_id:production,target_user_id:member,next_role:role});setMessage('Production role saved. Restrictions still apply.');});}}><label>Member<select required disabled={busy} value={member} onChange={e=>setMember(e.target.value)}><option value="">Choose a member</option>{directory.members.filter(m=>m.role==='member').map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></label><label>Role<select disabled={busy} value={role} onChange={e=>setRole(e.target.value)}><option value="organizer">Organizer</option><option value="editor">Editor</option><option value="viewer">Viewer</option></select></label><button disabled={!ready||busy||!member}>Assign role</button></form></details>}
  </>}
 </details>;
}
