'use client';
import { useEffect,useMemo,useRef,useState,type ReactNode } from 'react';
import type { SupabaseClient } from '@supabase/supabase-js';
import { DragDropContext,Droppable,Draggable,type DropResult } from '@hello-pangea/dnd';
import { createScheduleLibraryRepository,filterLibrary,libraryGroup,type LibraryRecord,type ProductionDestination,type LibraryFilter,type LibrarySort } from '@/lib/platform/schedule-library';
import { createLifecycleRepository } from '@/lib/platform/schedule-lifecycle-repository';
import { ScheduleLifecycleController } from '@/lib/platform/schedule-lifecycle-controller';
import type { ScheduleLifecycle,StoredSchedule } from '@/lib/platform/schedule-repository';
import { suggestedSlug } from '@/lib/platform/schedule-files';
import HubOrderButtons from '@/components/library/HubOrderButtons';
import LibrarySearch from '@/components/library/LibrarySearch';
import styles from '@/app/local-workspace/workspace.module.css';
import libraryStyles from './library.module.css';
type Props={review?:boolean;navigation?:ReactNode;client:SupabaseClient;actor:string|null;organization:string|null;enabled:boolean;selected:string|null;onOpen:(id:string)=>void;onInspect:(id:string)=>void;onState:(dirty:boolean,busy:boolean)=>void;onTransfer:(id:string,copy:boolean)=>void};
type PlacementAttempt={row:LibraryRecord;day:string|null;phase:string|null};
export default function LocalScheduleLibrary({review=false,navigation,client,actor,organization,enabled,selected,onOpen,onInspect,onState,onTransfer}:Props){
 const [repo]=useState(()=>createScheduleLibraryRepository(client)),[lifecycle]=useState(()=>createLifecycleRepository(client)),[controller]=useState(()=>new ScheduleLifecycleController());
 const [rows,setRows]=useState<LibraryRecord[]>([]),[destinations,setDestinations]=useState<ProductionDestination[]>([]),[loadedOrg,setLoadedOrg]=useState<string|null>(null),[loadedActor,setLoadedActor]=useState<string|null>(null);
 const [recent,setRecent]=useState<string[]>([]);
 const [showFilters,setShowFilters]=useState(false);
 const [query,setQuery]=useState(''),[status,setStatus]=useState<LibraryFilter>('active'),[production,setProduction]=useState(''),[from,setFrom]=useState(''),[to,setTo]=useState(''),[sort,setSort]=useState<LibrarySort>('manual');
 const [success,setSuccess]=useState('');
 const [message,setMessage]=useState(''),[busy,setBusy]=useState(false),[,redraw]=useState(0),busyRef=useRef(false),ticket=useRef(0),latest=useRef({actor,organization,enabled});latest.current={actor,organization,enabled};
 const [loading,setLoading]=useState(false),[loadError,setLoadError]=useState('');
 const [modal,setModal]=useState<'create'|'organize'|null>(null),[modalOrg,setModalOrg]=useState<string|null>(null),[modalActor,setModalActor]=useState<string|null>(null),[record,setRecord]=useState<StoredSchedule|null>(null),[row,setRow]=useState<LibraryRecord|null>(null);
 const [name,setName]=useState(''),[slug,setSlug]=useState(''),[destination,setDestination]=useState(''),[phase,setPhase]=useState(''),[day,setDay]=useState('');
 const [placement,setPlacement]=useState<PlacementAttempt|null>(null),[order,setOrder]=useState<LibraryRecord[]|null>(null),[orderActor,setOrderActor]=useState<string|null>(null),dialog=useRef<HTMLDialogElement>(null);
 const inventoryInScope=loadedOrg===organization&&loadedActor===actor;
 const orderInScope=order?.[0].organization_id===organization&&orderActor===actor;
 const currentModal=!!modal&&modalOrg===organization&&modalActor===actor&&enabled;
 useEffect(()=>{onState(!!modal||!!controller.attempt||!!placement||!!order,busy);},[modal,controller.attempt,placement,order,busy,onState]);
 useEffect(()=>{if(currentModal)dialog.current?.showModal();else dialog.current?.close();},[currentModal]);
 useEffect(()=>{controller.bind(actor);},[controller,actor]);
 useEffect(()=>{try{const data=JSON.parse(localStorage.getItem('roseland-library-recent:'+actor+':'+organization)||'[]');setRecent(Array.isArray(data)?data.filter(v=>typeof v==='string').slice(0,5):[]);}catch{setRecent([]);}},[actor,organization]);
 function openSchedule(id:string){setSuccess('');const next=[id,...recent.filter(v=>v!==id)].slice(0,5);setRecent(next);try{localStorage.setItem('roseland-library-recent:'+actor+':'+organization,JSON.stringify(next));}catch{}onOpen(id);}
 useEffect(()=>{setSuccess('');},[actor,organization,query,status,production,from,to,sort]);
 const current=()=>latest.current.actor===actor&&latest.current.organization===organization&&latest.current.enabled;
 async function load(){
  if(!actor||!organization||!enabled)return;
  const stamp=++ticket.current;setLoading(true);setLoadError('');
  try{const [inventory,choices]=await Promise.all([repo.inventory(actor,organization),repo.destinations(actor,organization)]);
   if(!current()||stamp!==ticket.current)return;
   setRows(inventory);setDestinations(choices);setLoadedOrg(organization);setLoadedActor(actor);
  }catch(e){if(current()&&stamp===ticket.current)setLoadError(e instanceof Error?e.message:'Library could not be loaded. Try Refresh library.');}
  finally{if(stamp===ticket.current)setLoading(false);}
 }
 async function run(work:()=>Promise<void>){if(!actor||!organization||!enabled||busyRef.current)return;busyRef.current=true;setBusy(true);try{await work();}catch(e){if(current())setMessage(e instanceof Error?e.message:'Library action failed. Your review is retained.');}finally{busyRef.current=false;setBusy(false);redraw(n=>n+1);}}
 useEffect(()=>{if(enabled&&actor&&organization)void load();else setLoading(false);return()=>{ticket.current++;};
 // Retain editor and action drafts across scope changes; all results are scope guarded.
 // eslint-disable-next-line react-hooks/exhaustive-deps
 },[actor,organization,enabled]);
 const filtered=useMemo(()=>filterLibrary(inventoryInScope?rows:[],query,status,production,from,to,sort),[rows,inventoryInScope,query,status,production,from,to,sort]);
 const selectedDestination=destinations.find(p=>p.id===destination);
 const canArrange=enabled&&!busy&&!modal&&!order&&status==='active'&&sort==='manual'&&!query&&!from&&!to;
 const canArrangeHubs=canArrange&&inventoryInScope&&!loading&&!loadError&&!production&&!controller.attempt&&!placement;
 function canMoveHub(index:number,direction:-1|1){const target=destinations[index],adjacent=destinations[index+direction];return !!(canArrangeHubs&&target?.organize&&adjacent?.organize&&Number.isSafeInteger(target.version)&&Number.isSafeInteger(adjacent.version));}
 async function moveHub(index:number,direction:-1|1){if(!canMoveHub(index,direction))return;const target=destinations[index],adjacent=destinations[index+direction];await run(async()=>{setMessage('');setSuccess('');try{await repo.moveHubs(actor!,target,adjacent);if(current()){await load();setSuccess('Production hub order saved.');}}catch{if(current()){setLoadError('The hub move is not confirmed. Refresh to see the saved order before moving again.');}}});}
 function clear(){setMessage('');controller.clear();setPlacement(null);setModal(null);setModalOrg(null);setRecord(null);setRow(null);setName('');setSlug('');redraw(n=>n+1);}
 function create(prod:string,ph=''){if(modal||controller.attempt||order)return;setMessage('');setSuccess('');setDestination(prod);setPhase(ph);setDay('');setName('');setSlug('');setRecord(null);setRow(null);setModalOrg(organization);setModalActor(actor);setModal('create');}
 async function organize(item:LibraryRecord){if(modal||controller.attempt||order)return;const saved=await lifecycle.read(actor!,organization!,item.id);if(!current())return;setMessage('');setSuccess('');setRecord(saved);setRow({...item,document_version:saved.document_version});setName(saved.display_name);setSlug(saved.slug);setDestination(saved.production_id);setPhase(saved.phase_id??item.effective_phase_id??'');setDay(saved.production_day_id??'');setModalOrg(organization);setModalActor(actor);setModal('organize');}
 function prepare(kind:ScheduleLifecycle){if(!record||controller.attempt||placement)return;try{controller.prepare(record,kind,kind==='rename'?{display_name:name.trim(),slug:slug.trim()}:{});redraw(n=>n+1);}catch(e){setMessage(e instanceof Error?e.message:'Check the action details.');}}
 async function confirm(checkOnly=false){await controller.execute(lifecycle,checkOnly);if(!current())return;if(controller.phase==='success'){setMessage('');const action=controller.attempt?.kind;setSuccess(action==='rename'?'Schedule renamed.':action==='archive'?'Schedule archived.':action==='unarchive'?'Schedule returned to Active.':action==='delete'?'Schedule moved to Trash.':action==='restore'?'Schedule restored from Trash.':'Schedule created.');await load();if(review&&controller.attempt?.kind==='create'){const id=controller.attempt.id;clear();openSchedule(id);}}else setMessage(controller.failure==='conflict'&&controller.attempt?.kind==='create'?'This schedule could not be created. The name may already be in use.':controller.failure?'The action is not confirmed. Keep this review and check the original saved result.':'Review the saved result before continuing.');redraw(n=>n+1);}
 async function place(checkOnly=false){if(!placement)return;if(checkOnly){const inventory=await repo.inventory(actor!,organization!);if(!current())return;const result=inventory.find(r=>r.id===placement.row.id);if(result&&result.document_version===placement.row.document_version+1&&result.production_day_id===placement.day&&(result.phase_id??null)===(placement.day?null:placement.phase)){setPlacement(null);setMessage('');setSuccess('Schedule placement confirmed.');await load();clear();}else setMessage('Exact placement is not confirmed. Keep the review or refresh before preparing a new request.');return;}
  await repo.place(actor!,placement.row,placement.day,placement.phase);if(!current())return;setPlacement(null);setMessage('');setSuccess('Schedule placement saved.');await load();clear();}
 async function arrange(items:LibraryRecord[]){setOrder(items);setOrderActor(actor);await repo.order(actor!,items);if(current()){setOrder(null);setMessage('');setSuccess('Library order saved.');await load();}}
 function drag(result:DropResult){if(!result.destination||!canArrange)return;if(result.source.droppableId!==result.destination.droppableId){setMessage('Drag within one section. Use Move to change sections.');return;}const items=filtered.filter(r=>libraryGroup(r)===result.source.droppableId);const [moved]=items.splice(result.source.index,1);if(!moved)return;items.splice(result.destination.index,0,moved);void run(()=>arrange(items));}
 async function checkOrder(){if(!order)return;const fresh=await repo.inventory(actor!,organization!);if(!current())return;if(order.every((r,i)=>fresh.some(v=>v.id===r.id&&v.library_position===i+1&&v.document_version>=r.document_version+1))){setOrder(null);setMessage('');setSuccess('Library order confirmed.');await load();}else setMessage('The requested order is not confirmed. Retry the original versions, or discard this review and refresh before arranging again.');}
 function section(prod:ProductionDestination,groupId:string,label:string,items:LibraryRecord[]){const draggable=canArrange&&items.every(r=>r.can_organize);return <details className="lbt-phase" open key={groupId}><summary className="lbt-phase-row"><span className="lbt-phase-name">{label}</span><span className="lbt-phase-count">{items.length}</span></summary><Droppable droppableId={groupId} isDropDisabled={!draggable}>{provided=><div className="lbt-sched-list" ref={provided.innerRef} {...provided.droppableProps}>{items.map((item,index)=><Draggable key={item.id} draggableId={item.id} index={index} isDragDisabled={!draggable}>{drag=><div className="lbt-sched-row" ref={drag.innerRef} {...drag.draggableProps}><span {...drag.dragHandleProps} aria-label={'Arrange '+item.display_name} title="Drag within this section">≡</span><button className="lbt-sched-name" aria-current={selected===item.id?'page':undefined} title={item.display_name} disabled={!enabled||busy||!!item.deleted_at} onClick={()=>openSchedule(item.id)}>{item.display_name}</button><small className={libraryStyles.metadata}>{[item.production_day_id===null?item.phase_name:item.day_number?`Day ${item.day_number}`:null,item.schedule_date].filter(Boolean).join(' · ')}{!item.can_edit?' · Read only':''}{item.status==='archived'?' · Archived':''}</small><button className="lbt-ctx-btn" title={'Organize '+item.display_name} aria-label={'Organize '+item.display_name} disabled={!enabled||busy||!!modal||!!order} onClick={()=>void run(()=>organize(item))}>⋯</button></div>}</Draggable>)}{provided.placeholder}</div>}</Droppable>{!items.length&&<p className="lbt-phase-row">No schedules in this section.</p>}</details>;}
 return <section aria-label="Schedule library" className={`${review?'lib-page':styles.shell} ${libraryStyles.library}`}>
  <div className={review?'lib-header':styles.directory}><h1 className={review?'lib-title':undefined}>{review?'Library':'Schedules'}</h1><div><button className="btn btn-light btn-sm" disabled={!enabled||busy||loading||!inventoryInScope||!!modal||!!order||!destinations.some(p=>p.create)} onClick={()=>create(destinations.find(p=>p.create)!.id)}>{review?'+ New Schedule':'New schedule'}</button> <button className="btn btn-light btn-sm" disabled={!enabled||busy||!!order} onClick={()=>void run(load)}>{review?'↻ Refresh':'Refresh library'}</button></div></div>
  {navigation}
  {review&&<div className="lib-search-row"><LibrarySearch value={query} onChange={setQuery}/><button className="btn btn-light btn-sm" aria-expanded={showFilters} onClick={()=>setShowFilters(v=>!v)}>Filter{[production,status!=='active',from,to,sort!=='manual'].filter(Boolean).length>0?` (${[production,status!=='active',from,to,sort!=='manual'].filter(Boolean).length})`:''}</button></div>}
  <div hidden={review&&!showFilters} className={`${styles.directory} ${review?libraryStyles.filters:''}`}><label hidden={review}>Search schedules<input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Name, production, phase or town"/></label><label>Production filter<select value={production} onChange={e=>setProduction(e.target.value)}><option value="">All productions</option>{destinations.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Collection<select value={status} onChange={e=>setStatus(e.target.value as LibraryFilter)}><option value="active">Active</option><option value="archived">Archived</option><option value="all">All saved</option><option value="trash">Trash</option></select></label><label>Sort schedules<select value={sort} onChange={e=>setSort(e.target.value as LibrarySort)}><option value="manual">Manual / day order</option><option value="name">Name</option><option value="date">Schedule date</option><option value="updated">Recently saved</option></select></label></div>
  <details hidden={review&&!showFilters}><summary>Date filter</summary><div className={`${styles.directory} ${review?libraryStyles.filters:''}`}><label>From date<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>To date<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label></div></details>
  {(!review||showFilters)&&<button className="btn btn-light btn-sm" onClick={()=>{setProduction('');setStatus('active');setSort('manual');setFrom('');setTo('');}}>Clear filters</button>}
  <p hidden={!busy&&!message&&!success} role="status">{busy?'Saving or reviewing… ':''}{message||success}</p>{loadError&&<p role="alert">Library could not be refreshed: {loadError} Use Refresh library to try again.</p>}<p hidden={review&&!loading&&inventoryInScope&&!query&&!loadError} role="status">{loading?'Loading complete library…':inventoryInScope?review?`${filtered.length} ${filtered.length===1?'schedule':'schedules'}`:`${filtered.length} visible schedules · Search includes every loaded page`:!organization?'Choose an organization to see its schedules.':!enabled?'Checking access to this library…':loadError?'Library unavailable.':'Preparing library…'}</p>
  {order&&!orderInScope&&<p>A library order review is retained in another organization. Return there to continue.</p>}{order&&orderInScope&&<div role="status"><p>Library order is awaiting confirmation. Original versions and order are retained.</p><button className="btn btn-light btn-sm" disabled={busy||!enabled} onClick={()=>void run(checkOrder)}>Check saved order</button><button className="btn btn-light btn-sm" disabled={busy||!enabled} onClick={()=>void run(()=>arrange(order))}>Retry original order</button><button className="btn btn-light btn-sm" disabled={busy} onClick={()=>{setOrder(null);setMessage('Order review discarded. Refresh before another arrangement.');}}>Discard order review</button></div>}
  {!query&&!production&&status==='active'&&!from&&!to&&inventoryInScope&&recent.some(id=>rows.some(r=>r.id===id&&!r.deleted_at))&&<div className="lib-recent" aria-label="Recent schedules"><div className="lib-recent-label">Recent</div>{recent.map(id=>rows.find(r=>r.id===id&&!r.deleted_at)).filter((r):r is LibraryRecord=>!!r).map(r=><div className="lib-recent-item" key={r.id}><button className="lib-recent-name" title={r.display_name} disabled={!enabled||busy} onClick={()=>openSchedule(r.id)}>{r.display_name}</button><span className="lib-recent-meta">{[r.production_name,r.phase_name].filter(Boolean).join(' / ')}</span>{r.schedule_date&&<span className="lib-recent-time">{r.schedule_date}</span>}</div>)}</div>}
  <DragDropContext onDragEnd={drag}><div className="lbt-tree">{(inventoryInScope?destinations:[]).filter(p=>!production||p.id===production).map(p=>{const hubIndex=destinations.findIndex(item=>item.id===p.id);const group=filtered.filter(r=>r.production_id===p.id);if((query||from||to)&&!group.length)return null;const assigned=group.filter(r=>r.production_day_id!==null),unassigned=group.filter(r=>r.production_day_id===null);const phaseIds=[...new Set(assigned.map(r=>r.effective_phase_id))];return <details key={p.id} className="lbt-prod" open><summary className="lbt-prod-row"><span className="lbt-prod-name">{p.name}</span><span className="lbt-prod-count">{group.length} {group.length===1?'schedule':'schedules'}</span><HubOrderButtons name={p.name} up={canMoveHub(hubIndex,-1)} down={canMoveHub(hubIndex,1)} onMove={direction=>void moveHub(hubIndex,direction)}/></summary>{phaseIds.map(id=>section(p,p.id+':'+(id??'no-phase'),p.phases.find(f=>f.id===id)?.name??'No phase',assigned.filter(r=>r.effective_phase_id===id)))}{section(p,p.id+':unassigned','No production day',unassigned)}{p.create&&<button className={`btn btn-light btn-sm ${libraryStyles.newInProduction}`} disabled={busy||!!modal||!!order} onClick={()=>create(p.id)}>+ New schedule in {p.name}</button>}</details>;})}</div></DragDropContext>
  {inventoryInScope&&!filtered.length&&<div className="empty"><strong>{rows.length?'No schedules match these filters.':'No schedules yet.'}</strong><p>{rows.length?'Try a different search or clear the filters.':destinations.some(p=>p.create)?'Create a schedule to get started.':'Schedules you can access will appear here.'}</p></div>}
  <dialog ref={dialog} className={`${styles.dialog} ${review?libraryStyles.reviewDialog:''}`} aria-label={modal==='create'?'New schedule':'Organize schedule'} onCancel={e=>{if(busy||controller.attempt||placement){e.preventDefault();return;}clear();}}>
   <h2>{modal==='create'?'New schedule':record?.display_name}</h2><p role="status">{message||success}</p>{!review&&<p>Saved actions keep any open editor draft. A day is optional; Unassigned stays within its production.</p>}
   {!controller.attempt&&!placement&&<><div className={`${styles.login} ${libraryStyles.form}`}><label>Schedule name<input value={name} disabled={busy||modal==='organize'&&!row?.can_organize} onChange={e=>{setName(e.target.value);if(modal==='create')setSlug(suggestedSlug(e.target.value));}}/></label><label hidden={review}>Address name<input value={slug} disabled={busy||modal==='organize'&&!row?.can_organize} onChange={e=>setSlug(e.target.value)}/></label><label>Production<select value={destination} disabled={busy||modal==='organize'} onChange={e=>{const p=destinations.find(p=>p.id===e.target.value);setDestination(e.target.value);setPhase(previous=>p?.phases.some(f=>f.id===previous)?previous:'');setDay('');}}>{destinations.filter(p=>modal==='organize'||p.create).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Phase<select value={phase} disabled={busy||!!day||modal==='organize'&&!row?.can_organize} onChange={e=>setPhase(e.target.value)}><option value="">No phase</option>{selectedDestination?.phases.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Production day<select value={day} disabled={busy||modal==='organize'&&!row?.can_organize} onChange={e=>{setDay(e.target.value);if(e.target.value)setPhase(selectedDestination?.days.find(d=>d.id===e.target.value)?.phase??'');}}><option value="">Unassigned</option>{selectedDestination?.days.map(d=><option key={d.id} value={d.id}>{d.number?`Day ${d.number}`:`Day ${d.position+1}`}{d.date?' · '+d.date:''}</option>)}</select></label></div>
    {modal==='create'?<button className="btn btn-pink" disabled={busy||!name.trim()||!slug||!selectedDestination?.create} onClick={()=>void run(async()=>{controller.prepareCreate(organization!,crypto.randomUUID(),day||null,name.trim(),slug.trim(),{meta:{projectName:selectedDestination!.name,phase:selectedDestination!.phases.find(p=>p.id===phase)?.name??''},rows:[]} as unknown as StoredSchedule['document'],{productionId:destination,phaseId:phase||null});redraw(n=>n+1);if(review)await confirm();})}>{review?'Create schedule':'Review creation'}</button>:<div>
     {!record?.deleted_at&&<><button className="btn btn-light btn-sm" disabled={busy||!row?.can_organize} onClick={()=>prepare('rename')}>Review rename</button><button className="btn btn-light btn-sm" disabled={busy||!row?.can_organize} onClick={()=>{if(row)setPlacement({row,day:day||null,phase:phase||null});}}>Review placement</button><button className="btn btn-light btn-sm" disabled={busy||!row?.can_organize} onClick={()=>prepare(record?.status==='archived'?'unarchive':'archive')}>{record?.status==='archived'?'Review unarchive':'Review archive'}</button></>}
     <button className="btn btn-light btn-sm" disabled={busy||!row?.can_trash} onClick={()=>prepare(record?.deleted_at?'restore':'delete')}>{record?.deleted_at?'Review recovery':'Move to Trash'}</button><button className="btn btn-light btn-sm" disabled={busy||!row?.can_transfer||!!record?.deleted_at} onClick={()=>{const id=record!.id;clear();onTransfer(id,false);}}>Move to production</button><button className="btn btn-light btn-sm" disabled={busy||!row?.can_copy||!!record?.deleted_at} onClick={()=>{const id=record!.id;clear();onTransfer(id,true);}}>Duplicate</button><button className="btn btn-light btn-sm" disabled={busy} onClick={()=>{const id=record!.id;clear();onInspect(id);}}>History and version restore</button>
    </div>}
   </>}
   {controller.attempt&&<><p>{controller.attempt.kind==='rename'?<>Rename <strong>{controller.attempt.name}</strong> to <strong>{String(controller.attempt.payload.display_name)}</strong>.</>:<>{controller.attempt.kind==='delete'?'Move to Trash':controller.attempt.kind==='restore'?'Restore from Trash':controller.attempt.kind==='unarchive'?'Unarchive':controller.attempt.kind==='archive'?'Archive':'Create'} <strong>{controller.attempt.name}</strong>.</>} {controller.phase==='success'?'Confirmed.':'Schedule content will stay intact.'}</p>{controller.failure&&<p role="alert">{controller.failure==='conflict'&&controller.attempt.kind==='create'?'Check the original result, or discard this review and choose a different name.':'Keep this review and check the saved result before trying again.'}</p>}{controller.phase!=='success'&&<div><button className="btn btn-light btn-sm" disabled={busy||!enabled||controller.phase==='conflict'} onClick={()=>void run(()=>confirm())}>Confirm reviewed action</button><button className="btn btn-light btn-sm" disabled={busy||!enabled} onClick={()=>void run(()=>confirm(true))}>Check original result</button></div>}</>}
   {placement&&<><p>Assign {placement.day?'the selected existing day':'Unassigned'} at saved version {placement.row.document_version}. Document date, location and content stay unchanged.</p><button className="btn btn-light btn-sm" disabled={busy||!enabled} onClick={()=>void run(()=>place())}>Confirm placement</button><button className="btn btn-light btn-sm" disabled={busy||!enabled} onClick={()=>void run(()=>place(true))}>Check placement result</button></>}
   {controller.phase==='success'&&controller.attempt?.kind==='create'&&<button className="btn btn-light btn-sm" disabled={busy||!enabled} onClick={()=>{const id=controller.attempt!.id;clear();openSchedule(id);}}>Open created schedule</button>}
   <button className="btn btn-light btn-sm" disabled={busy} onClick={clear}>{controller.phase==='success'?'Close confirmed result':controller.attempt||placement?'Discard local review':'Cancel'}</button>
  </dialog>
 </section>;
}
