'use client';
import {useMemo,useRef,useState} from 'react';
import type {SupabaseClient} from '@supabase/supabase-js';
import {captureClientLink,createClientLinksRepository,type ClientLink,type ClientLinkAttempt,type LinkReview} from '@/lib/platform/client-links';
export default function LocalScheduleSharing({workspacePath='/local-workspace',client,actor,organization,schedule,enabled,readOnly}:{workspacePath?:'/review'|'/local-workspace';client:SupabaseClient;actor:string|null;organization:string;schedule:string;enabled:boolean;readOnly:boolean}){
 const repository=useMemo(()=>createClientLinksRepository(client),[client]),[review,setReview]=useState<LinkReview|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState('Client links show the saved schedule, including row notes. Contacts, call sheets, status and history are excluded.'),[url,setUrl]=useState(''),[confirm,setConfirm]=useState<ClientLink|null>(null);
 const pending=useRef<ClientLinkAttempt|null>(null),working=useRef(false),current=useRef({actor,schedule,enabled});current.current={actor,schedule,enabled};
 async function run(work:()=>Promise<void>){if(!actor||!enabled||working.current)return;working.current=true;setBusy(true);try{await work();}catch(e){if(current.current.actor===actor&&current.current.schedule===schedule)setMessage(e instanceof Error?e.message:'Sharing unavailable.');}finally{working.current=false;setBusy(false);}}
 function same(){return current.current.actor===actor&&current.current.schedule===schedule&&current.current.enabled;}
 async function load(append=false){if(!actor)return;const data=await repository.read(actor,schedule,append?review?.links.at(-1)?.id??null:null);if(same())setReview(append?{...data,links:[...(review?.links??[]),...data.links]}:data);}
 async function create(){if(!actor||!review)return;pending.current??=await captureClientLink(actor,schedule,review.version);const attempt=pending.current;const receipt=await repository.create(attempt);if(!same())return;if(receipt.revoked){setUrl('');setMessage('This request already created a link that was revoked. Refresh to create another.');}else{setUrl(`${window.location.origin}/local-client#${attempt.token}`);setMessage(`Client link expires ${new Date(receipt.expires_at).toLocaleString()}. Anyone with this link can read the selected Client fields.`);}pending.current=null;await load();}
 async function copy(value:string){try{await navigator.clipboard.writeText(value);setMessage('Link copied.');}catch{setUrl(value);setMessage('Select and copy the link below.');}}
 return <details onToggle={e=>{if(e.currentTarget.open&&!review)void run(()=>load());}}><summary>Team and Client links</summary><p role="status">{message}</p><button className="btn btn-light btn-sm" disabled={!enabled||busy} onClick={()=>void copy(`${window.location.origin}${workspacePath}?screen=schedule&org=${organization}&schedule=${schedule}`)}>Copy Team link</button> <button className="btn btn-light btn-sm" disabled={!enabled||readOnly||busy||!review?.can_create} onClick={()=>void run(create)}>{pending.current?'Retry same Client link':'Create Client link'}</button> <button disabled={!enabled||busy} onClick={()=>void run(async()=>{pending.current=null;await load();})}>Refresh links</button>
 {url&&<p><label>Link <input readOnly value={url} onFocus={e=>e.target.select()} style={{width:'75%'}}/></label> <button onClick={()=>void copy(url)}>Copy link</button></p>}
 {review&&<ul>{review.links.map(link=><li key={link.id}>{link.kind==='legacy'?'Legacy route (all original valid links)':'Client link'} · {new Date(link.created_at).toLocaleString()} · {link.revoked_at?'Revoked':link.expires_at?`Expires ${new Date(link.expires_at).toLocaleString()}`:'Original token expiry applies'} {link.can_revoke&&!link.revoked_at&&<button disabled={busy||readOnly||!enabled} onClick={()=>setConfirm(link)}>Revoke</button>}</li>)}</ul>}
 {review&&review.links.length>0&&review.links.length%100===0&&<button disabled={busy} onClick={()=>void run(()=>load(true))}>Load more links</button>}
 {confirm&&<div role="alert"><p>{confirm.kind==='legacy'?'Revoke every original link for this legacy route?':'Revoke this Client link?'} Existing copies already downloaded cannot be recalled.</p><button disabled={busy||readOnly||!enabled} onClick={()=>void run(async()=>{await repository.revoke(actor!,schedule,confirm);if(same()){setConfirm(null);setUrl('');setMessage('Revoked. Future requests are denied.');await load();}})}>Confirm revoke</button> <button disabled={busy} onClick={()=>setConfirm(null)}>Keep link</button></div>}
 </details>;
}
