import{readFileSync,writeFileSync}from'node:fs';import{randomUUID,createHash}from'node:crypto';import{client,sql,totp}from'../b13-local.ts';
const file='/private/tmp/roseland-b14-fixtures.json',f=JSON.parse(readFileSync(file,'utf8'));const checks:string[]=[];
const owner=client(),editor=client(),outsider=client(),viewer=client();for(const [c,u]of [[owner,f.owner],[editor,f.editor],[outsider,f.outsider],[viewer,f.viewer]]as const){if((await c.auth.signInWithPassword(u)).error)throw Error('Fictional login failed');}
if((await owner.auth.mfa.challengeAndVerify({factorId:f.owner.factor.id,code:totp(f.owner.factor.secret)})).error)throw Error('Owner MFA failed');
async function rpc(c:any,n:string,a:any){const r=await c.rpc(n,a);if(r.error)throw Error(n+': '+r.error.message);checks.push(n);return r.data;}
const before=await rpc(editor,'read_schedule',{target_schedule_id:f.schedule});const document=structuredClone(before.document);document.meta.town='B14 newest source edit';document.rows[0].notes='B14 latest recoverable note';const saved=await rpc(editor,'update_schedule_document',{target_schedule_id:f.schedule,expected_version:before.document_version,next_document:document,schema_version:1});
await rpc(owner,'save_organization_presentation',{target_organization_id:f.organization,request_id:randomUUID(),expected_version:1,next_config:{labels:{hdrTitle:'B14 latest organization labels'},colors:{'--pink':'#ff88aa'}}});
await rpc(owner,'mutate_schedule_template',{request_id:randomUUID(),target_template_id:f.template,target_production_id:f.production,expected_version:1,operation:'rename',next_name:'B14 newest template name'});
f.latestSnapshot=randomUUID();await rpc(editor,'mutate_schedule_snapshot',{request_id:randomUUID(),target_snapshot_id:f.latestSnapshot,target_schedule_id:f.schedule,expected_version:0,operation:'capture',next_name:'B14 latest snapshot',next_document:document,source_version:saved.document_version});
f.restriction=randomUUID();await rpc(owner,'set_schedule_restriction',{target_id:f.restriction,target_organization_id:f.organization,target_production_id:f.production,target_schedule_id:f.schedule,subject_role:null,subject_user_id:f.viewer.id,denied_actions:['export'],expected_revision:0});
f.viewerMembership=sql(`select id from public.organization_memberships where organization_id='${f.organization}' and user_id='${f.viewer.id}'`);await rpc(owner,'set_organization_member_status',{target_organization_id:f.organization,target_membership_id:f.viewerMembership,expected_revision:1,request_id:randomUUID(),next_status:'suspended',confirmed:true,reason:'Fictional B14 latest membership state'});
f.revokedSession=(await viewer.auth.getSession()).data.session!.access_token;await viewer.auth.signOut();
const enrolled=await outsider.auth.mfa.enroll({factorType:'totp',friendlyName:'B14 independent owner'});if(enrolled.error||!enrolled.data)throw Error('Outsider enrollment failed');f.outsider.factor={id:enrolled.data.id,secret:enrolled.data.totp.secret};if((await outsider.auth.mfa.challengeAndVerify({factorId:enrolled.data.id,code:totp(enrolled.data.totp.secret)})).error)throw Error('Independent MFA failed');
await rpc(outsider,'request_organization_deletion',{target_organization_id:f.otherOrg,request_id:randomUUID(),expected_version:0,confirmed:true});
f.expectedDocument=document;f.expectedVersion=saved.document_version;writeFileSync(file,JSON.stringify(f,null,2),{mode:0o600});writeFileSync('evidence/b14-restore/newer-edits.json',JSON.stringify({checks,version:saved.document_version,pendingDeletionOtherOrganization:true,revokedSessionCapturedPrivately:true},null,2)+'\n');console.log('PASS '+checks.length+' genuine newer source operations');
