import{writeFileSync}from'node:fs';import{isDeepStrictEqual}from'node:util';import{randomUUID,createHash}from'node:crypto';import{project,config,f,client,admin,login,totp,port}from'./b14-runtime.ts';
const checks:string[]=[];function check(v:unknown,s:string){if(!v)throw Error(s);checks.push(s);console.log('PASS '+s);}
async function rpc(c:any,n:string,a:any){const r=await c.rpc(n,a);if(r.error)throw Error(n+': '+r.error.message);return r.data;}
const owner=await login(f.owner);check(!!(await owner.rpc('read_schedule',{target_schedule_id:f.schedule})).error,'Restored owner password alone cannot bypass MFA');check(!(await owner.auth.mfa.challengeAndVerify({factorId:f.owner.factor.id,code:totp(f.owner.factor.secret)})).error,'Restored original TOTP factor verifies genuinely');
const editor=await login(f.editor),viewer=await login(f.viewer),outsider=await login(f.outsider,true);const expected=project.endsWith('g2')?f.destinationDocument:f.expectedDocument,version=project.endsWith('g2')?f.destinationVersion:f.expectedVersion;
for(const [c,label]of [[owner,'owner'],[editor,'editor']]as const){const row=await rpc(c,'read_schedule',{target_schedule_id:f.schedule});check(row.document_version===version&&isDeepStrictEqual(row.document,expected),'Complete latest document and version through '+label);}
check(!!(await viewer.rpc('read_schedule',{target_schedule_id:f.schedule})).error,'Restored suspended membership denies access');check((await outsider.from('schedules').select('id').eq('id',f.schedule)).data?.length===0,'Restored cross-organization read remains hidden');
const template=await rpc(editor,'read_schedule_template',{target_template_id:f.template});check(template.name==='B14 newest template name'&&template.version===2,'Newest template/version/provenance readable');const snapshot=await rpc(editor,'read_schedule_snapshot',{target_snapshot_id:f.latestSnapshot});check(isDeepStrictEqual(snapshot.document,f.expectedDocument),'Restored newest source snapshot retains complete document');
const cms=await rpc(owner,'read_organization_presentation',{target_organization_id:f.organization});check(JSON.stringify(cms).includes('B14 latest organization labels'),'Newest organization presentation readable');
const life=await rpc(outsider,'read_organization_lifecycle',{target_organization_id:f.otherOrg});check(JSON.stringify(life).includes('pending_deletion'),'Pending organization deletion state preserved');check(!!(await outsider.rpc('save_organization_presentation',{target_organization_id:f.otherOrg,request_id:randomUUID(),expected_version:0,next_config:{labels:{hdrTitle:'Must remain frozen'}}})).error,'Restored pending-deletion organization rejects writes');
const revoked=await fetch(config.API_URL+'/rest/v1/schedules?select=id',{headers:{apikey:config.ANON_KEY,authorization:'Bearer '+f.revokedSession}});check(revoked.status===401,'Previously revoked genuine session remains denied');
check(await rpc(admin,'read_schedule_client_view',{token_hash:createHash('sha256').update(f.revokedToken).digest('hex')})===null,'Previously revoked Client link remains denied');const shared=await rpc(admin,'read_schedule_client_view',{token_hash:createHash('sha256').update(f.liveToken).digest('hex')});check(shared.document.rows[0].notes===expected.rows[0].notes&&!JSON.stringify(shared).includes('PRIVATE'),'Restored current Client projection preserves allowlist');
const http=await fetch('http://127.0.0.1:'+port+'/api/platform/local-client-view',{method:'POST',headers:{'content-type':'application/json',origin:'http://127.0.0.1:'+port},body:JSON.stringify({token:f.liveToken})});check(http.ok&&(await http.json()).document.rows[0].notes===expected.rows[0].notes,'Reviewed application reads restored Client data');
let sourceClosed=false;try{await fetch('http://127.0.0.1:56321/rest/v1/schedules',{method:'POST',headers:{'content-type':'application/json'},body:'{}',signal:AbortSignal.timeout(2000)});}catch{sourceClosed=true;}check(sourceClosed,'Original source API remains stopped and denies new writes');
writeFileSync('evidence/b14-restore/'+project+'-readback.json',JSON.stringify({checks,version,providerRaceInvestigation:false},null,2)+'\n');
