import test from 'node:test';
import assert from 'node:assert/strict';
import { contactsCsv, documentContacts, safeDownloadName } from '../../lib/document-tools.ts';
import { fictionalDocumentProviders as providers } from '../../lib/platform/document-providers.ts';
import type { ScheduleRow } from '../../lib/types.ts';
const row=(patch:Partial<ScheduleRow>={})=>({contactName:'Example Crew',contactTitle:'Producer',contactPhone:'+1 202 555 0142',contactEmail:'crew@example.test',timeIn:'9:00 AM',action:'Other',otherText:'Test',desc:'Two lines\nwith "quotes", comma',loc:'Legacy place',...patch} as ScheduleRow);
function parse(text:string){const result:string[][]=[];let cells:string[]=[],v='',quoted=false;for(let i=1;i<text.length;i++){const c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){v+='"';i++;}else quoted=!quoted;}else if(c===','&&!quoted){cells.push(v);v='';}else if(c==='\r'&&!quoted&&text[i+1]==='\n'){cells.push(v);result.push(cells);cells=[];v='';i++;}else v+=c;}assert.equal(quoted,false);return result;}
test('CSV round-trips quoted multiline Unicode and intended row context with formula-safe values',()=>{const source=row({contactName:'=SUM(1,2)',contactTitle:'\t@evil',contactEmail:'雪@example.test',locName:'Short',locAddress:'Full address',subLocations:[{id:'sub',loc:'Nested legacy',name:'Nested name',address:'Nested address',desc:'Nested\ndescription'}]});const parsed=parse(contactsCsv(documentContacts([source])));assert.equal(parsed.length,2);assert.deepEqual(parsed[0],['Name','Title','Phone','Email','Time In','Action','Location','Description']);assert.deepEqual(parsed[1],["'=SUM(1,2)","'\t@evil","'+1 202 555 0142",'雪@example.test','9:00 AM','Test','Legacy place',source.desc]);});
test('CSV neutralizes formula prefixes in every column without altering ordinary text',()=>{for(const value of ['=cmd','+cmd','-cmd','@cmd',' \t=cmd','\rtext','\ntext']){const contact={name:value,title:value,phone:value,email:value,rows:[{timeIn:value,action:value,loc:value,desc:value}]};assert.ok(parse(contactsCsv([contact]))[1].every(v=>v==="'"+value));}assert.equal(parse(contactsCsv(documentContacts([row({contactName:'Alice – Fictional'})])))[1][0],'Alice – Fictional');});
test('contact grouping preserves differing titles and emails, duplicate contexts, and title-only contacts',()=>{const data=documentContacts([row(),row(),row({contactTitle:'Camera'}),row({contactEmail:'second@example.test'}),row({contactName:'',contactTitle:'Crew',contactPhone:'',contactEmail:''}),row({sunLocked:true})]);assert.equal(data.length,4);assert.equal(data[0].rows.length,2);assert.equal(data[3].title,'Crew');assert.equal(documentContacts([row({contactName:'',contactTitle:'',contactPhone:'',contactEmail:''})]).length,0);});
test('safe download names strip filesystem separators, controls, and dot traversal',()=>{assert.equal(safeDownloadName('..','contacts.csv'),'Schedule-contacts.csv');for(const value of ['../../path\u0000','a\\b:c?d*e','x'.repeat(300)]){const n=safeDownloadName(value,'contacts.csv');assert.ok(!/[\\/\u0000-\u001f:<>?*|]/.test(n));assert.ok(n.length<=113);assert.ok(!n.startsWith('.'));}});
test('fictional providers preserve zero coordinates, sun-only, unavailable and invalid data without network',async()=>{const old=globalThis.fetch;globalThis.fetch=()=>{throw new Error('Network forbidden');};try{const found=await providers.search('woodland');assert.equal(found.length,1);const geo=await providers.geocode(found[0].placeId);assert.equal(geo?.lat,0);assert.equal(geo?.lng,0);assert.equal((await providers.weather('2026-10-20',0,0,'Zero'))?.town,'Zero');assert.equal((await providers.weather('2026-10-20',12,12,'Sun'))?.noForecast,true);for(const [date,lat,lng] of [['2026-02-30',0,0],['invalid',0,0],['2026-10-20',NaN,0],['2026-10-20',91,0],['2026-10-20',0,181],['2026-10-20',13,13]] as const)assert.equal(await providers.weather(date,lat,lng,'Unavailable'),null);assert.equal(await providers.geocode('unknown'),null);assert.deepEqual(await providers.search(''),[]);}finally{globalThis.fetch=old;}});
