import test from 'node:test';
import assert from 'node:assert/strict';
import type {SupabaseClient} from '@supabase/supabase-js';
import {captureLifecycleAttempt,createOrganizationLifecycleRepository,LifecycleError} from '../../lib/platform/organization-lifecycle.ts';
const a={actor:'10000000-0000-4000-8000-000000000001',organization:'10000000-0000-4000-8000-000000000002',request:'10000000-0000-4000-8000-000000000003',version:0,operation:'request' as const,confirmed:true};
function fixture(actor=a.actor,result:unknown={data:{confirmed:true,organization_id:a.organization,request_id:a.request,operation:a.operation,version:1},error:null}){const calls:unknown[]=[];const c={auth:{getSession:async()=>({data:{session:{user:{id:actor},access_token:'current-token'}}})},rpc:(name:string,args:unknown)=>{calls.push({name,args});return {setHeader:()=>Promise.resolve(result)};}} as unknown as SupabaseClient;return {repo:createOrganizationLifecycleRepository(c),calls};}
test('lifecycle confirmation and version are immutable for exact retry',()=>{assert.throws(()=>captureLifecycleAttempt({...a,confirmed:false}));const draft={...a},request=captureLifecycleAttempt(draft);draft.version=3;assert.equal(request.version,0);assert.ok(Object.isFrozen(request));});
test('lifecycle account switch cannot send an old actor request',async()=>{const x=fixture('10000000-0000-4000-8000-000000000009');await assert.rejects(x.repo.save(a),(e)=>e instanceof LifecycleError&&e.kind==='auth');assert.equal(x.calls.length,0);});
test('retries use identical request identity and do not change expected version',async()=>{const x=fixture();await x.repo.save(a);await x.repo.save(a);assert.deepEqual(x.calls[0],x.calls[1]);});
test('mismatched lifecycle receipt remains unconfirmed',async()=>{await assert.rejects(fixture(a.actor,{data:{confirmed:true,organization_id:a.organization,request_id:a.request,operation:'cancel',version:1},error:null}).repo.save(a),(e)=>e instanceof LifecycleError&&e.kind==='unknown');});
test('malformed lifecycle state cannot silently enable writes',async()=>{await assert.rejects(fixture(a.actor,{data:{organization_id:a.organization,version:1,state:'pending_deletion',read_only:false,can_request:false,can_cancel:false,can_manage:false,notifications:[]},error:null}).repo.read(a.actor,a.organization),(e)=>e instanceof LifecycleError&&e.kind==='unknown');});
