const test=require('node:test');const assert=require('node:assert/strict');const crypto=require('node:crypto');
const {sourceLoader}=require('../editor/source-loader.cjs');
const {NextRequest}=require('next/server');
const env={GOOGLE_PLACES_KEY:'fictional-provider-key',SCHEDULE_APP_PASSWORD:'fictional-password',SCHEDULE_AUTH_SECRET:'fictional-secret'};
const token=crypto.createHmac('sha256',env.SCHEDULE_AUTH_SECRET).update('editor:'+env.SCHEDULE_APP_PASSWORD).digest('hex');
async function run(fn){const old={...process.env},fetch=global.fetch;Object.assign(process.env,env);let calls=[];global.fetch=async(url,init)=>{calls.push({url,init});return new Response(JSON.stringify({suggestions:[],location:{latitude:1,longitude:2}}),{status:200,headers:{'content-type':'application/json'}});};try{await fn(sourceLoader()('app/api/places/route.ts'),calls);}finally{global.fetch=fetch;for(const k of Object.keys(env)){if(old[k]===undefined)delete process.env[k];else process.env[k]=old[k];}}}
function req(method='POST',headers={},body={input:'fictional place'}){return new NextRequest('http://localhost:3455/api/places'+(method==='GET'?'?placeId=fictional-place':''),{method,headers:{host:'localhost:3455','content-type':'application/json',...headers},...(method==='POST'?{body:JSON.stringify(body)}:{})});}
test('Forged UI flag cannot use provider proxy',async()=>run(async(route,calls)=>{const r=await route.POST(req('POST',{cookie:'rp_auth_flag=1'}));assert.equal(r.status,401);assert.equal(calls.length,0);}));
test('Valid existing editor token permits bounded private lookup',async()=>run(async(route,calls)=>{const r=await route.POST(req('POST',{authorization:'Bearer '+token,origin:'http://localhost:3455'}));assert.equal(r.status,200);assert.equal(calls.length,1);assert.match(r.headers.get('cache-control'),/no-store/);assert.equal(calls[0].init.redirect,'error');assert.ok(calls[0].init.signal);}));
test('Wrong token and foreign origin never reach provider',async()=>run(async(route,calls)=>{assert.equal((await route.GET(req('GET',{authorization:'Bearer '+'0'.repeat(64)}))).status,401);assert.equal((await route.POST(req('POST',{authorization:'Bearer '+token,origin:'https://outside.invalid'}))).status,403);assert.equal(calls.length,0);}));
test('Malformed and oversized bodies are refused before provider',async()=>run(async(route,calls)=>{const headers={authorization:'Bearer '+token};assert.equal((await route.POST(req('POST',headers,{input:{unexpected:1}}))).status,400);assert.equal((await route.POST(req('POST',headers,{input:'x'.repeat(17000)}))).status,413);assert.equal(calls.length,0);}));
test('Provider errors cannot enter response or logs',async()=>run(async(route,calls)=>{const original=console.error,logs=[];console.error=(...x)=>logs.push(x.join(' '));global.fetch=async()=>{throw Error('SECRET-FICTIONAL-PROVIDER-DIAGNOSTIC');};try{const r=await route.GET(req('GET',{authorization:'Bearer '+token}));assert.equal(r.status,502);assert.ok(!(await r.text()).includes('SECRET-'));assert.ok(!logs.join(' ').includes('SECRET-'));}finally{console.error=original;}}));
test('Process request budget is bounded and recovers after its window',()=>{const {createPlacesBudget}=sourceLoader()('lib/security/places-proxy.ts');const allow=createPlacesBudget(2,1000);assert.equal(allow(1000),true);assert.equal(allow(1001),true);assert.equal(allow(1002),false);assert.equal(allow(2001),true);});
