import test from 'node:test';
import assert from 'node:assert/strict';
import type { SupabaseClient } from '@supabase/supabase-js';
import { LocalEditorController } from '../../lib/platform/local-editor-controller.ts';
import { ScheduleRepositoryError, type StoredSchedule } from '../../lib/platform/schedule-repository.ts';
import { captureSaveAttempt, saveMatches, savedFromHistory, createSaveRecoveryRepository, type SaveAttempt, type SaveResult, type SaveRecoveryRepository } from '../../lib/platform/schedule-save-recovery.ts';
import type { ScheduleHistory } from '../../lib/platform/schedule-lifecycle-controller.ts';
import type { ScheduleData } from '../../lib/types.ts';
const actor='11111111-1111-4111-8111-111111111111',org='22222222-2222-4222-8222-222222222222',prod='33333333-3333-4333-8333-333333333333',day='44444444-4444-4444-8444-444444444444',id='55555555-5555-4555-8555-555555555555';
const before={id,organization_id:org,production_id:prod,production_day_id:day,display_name:'Fictional day',slug:'fictional-day',status:'draft',archived_from_status:null,deleted_at:null,document_schema_version:1,document_version:3,document:{meta:{town:'Before'},rows:[]},updated_at:'2026-09-16T08:00:00Z',updated_by:actor} as unknown as StoredSchedule;
const document={meta:{town:'Attempt',callsheet:{notes:'Full document'}},rows:[{notes:'First',subLocations:[{id:'one',loc:'Lane',done:false}]}],savedAt:123} as ScheduleData;
function attempt(){return captureSaveAttempt({actor,before,document,documentSession:1,editRevision:1});}
function saved(a=attempt()){return {...a.before,document:a.document,document_version:4,updated_at:'2026-09-16T09:00:00Z'};}
function history(r=saved()):ScheduleHistory{return {schedule_id:r.id,organization_id:r.organization_id,production_id:r.production_id,version:r.document_version,document_schema_version:r.document_schema_version,document:r.document,metadata:{display_name:r.display_name,slug:r.slug,production_day_id:r.production_day_id,status:r.status,archived_from_status:r.archived_from_status,deleted_at:r.deleted_at},created_by:r.updated_by,created_at:r.updated_at,checksum:'a'.repeat(64),metadata_checksum:'b'.repeat(64)};}
function deferred<T>(){let resolve!:(v:T)=>void;const promise=new Promise<T>(r=>{resolve=r;});return {promise,resolve};}
function harness(){
 let dirty=true,loads=0,doc=structuredClone(document);const sent:SaveAttempt[]=[];
 const state={documentSession:1,editRevision:1,getScheduleData:()=>doc,markClean:()=>{dirty=false;}};
 const repo:SaveRecoveryRepository={read:async()=>before,send:async a=>{sent.push(a);throw new ScheduleRepositoryError('failed');},probe:async()=>({state:'retryable',saved:null,currentVersion:3})};
 const c=new LocalEditorController(repo,{getState:()=>state,load:r=>{loads++;state.documentSession++;state.editRevision++;doc=r.document as ScheduleData;dirty=false;}});c.bind(actor);c.record=structuredClone(before);
 return {c,repo,state,sent,dirty:()=>dirty,loads:()=>loads,edit(){state.editRevision++;doc.meta.town='Newer draft';dirty=true;},doc:()=>doc};
}
test('attempt deeply captures actor, baseline and every optional document value',()=>{const input={actor,before:structuredClone(before),document:structuredClone(document),documentSession:1,editRevision:1};const a=captureSaveAttempt(input);input.before.document_version=99;input.document.rows[0].notes='Changed';assert.equal(a.before.document_version,3);assert.equal(a.document.rows![0].notes,'First');assert.ok(Object.isFrozen(a.document.rows![0].subLocations));assert.throws(()=>{a.document.meta!.town='No';});});
test('send failure retains exact attempt; new save and unreviewed retry cannot dispatch',async()=>{const h=harness();await assert.rejects(h.c.save(),{kind:'failed'});const a=h.c.attempt;h.edit();assert.equal(await h.c.save(),false);assert.equal(await h.c.recover(true),false);assert.equal(h.sent.length,1);assert.equal(h.c.attempt,a);assert.equal(a?.document.meta?.town,'Attempt');assert.equal(h.dirty(),true);});
test('lost committed response confirms without a write and retains edits/undo revision',async()=>{const h=harness();await assert.rejects(h.c.save());const a=h.c.attempt!;h.edit();h.repo.probe=async()=>({state:'matched',saved:saved(a),currentVersion:4});assert.equal(await h.c.recover(),true);assert.equal(h.sent.length,1);assert.equal(h.c.record?.document_version,4);assert.equal(h.c.attempt,null);assert.equal(h.doc().meta.town,'Newer draft');assert.equal(h.dirty(),true);assert.equal(h.loads(),0);});
test('confirmed current attempt becomes clean only at the captured edit revision',async()=>{const h=harness();await assert.rejects(h.c.save());h.repo.probe=async()=>({state:'matched',saved:saved(h.c.attempt!),currentVersion:4});await h.c.recover();assert.equal(h.dirty(),false);assert.equal(h.loads(),0);});
test('later server version is reported but never adopted as a writable baseline',async()=>{const h=harness();await assert.rejects(h.c.save());const a=h.c.attempt!;h.repo.probe=async()=>({state:'matched',saved:saved(a),currentVersion:5});await h.c.recover();assert.equal(h.c.record?.document_version,4);assert.equal(h.c.result?.currentVersion,5);assert.equal(h.c.attempt,a);assert.equal(h.dirty(),true);assert.equal(await h.c.save(),false);assert.equal(await h.c.recover(true),false);});
test('exact retry probes again and sends the frozen document, never newer edits',async()=>{const h=harness();await assert.rejects(h.c.save());const a=h.c.attempt!;let probes=0;h.repo.probe=async()=>{probes++;return {state:'retryable',saved:null,currentVersion:3};};await h.c.recover();h.edit();h.repo.send=async value=>{h.sent.push(value);return saved(value);};await h.c.recover(true);assert.equal(probes,2);assert.equal(h.sent[1],a);assert.equal(h.sent[1].document.meta?.town,'Attempt');assert.equal(h.doc().meta.town,'Newer draft');assert.equal(h.dirty(),true);});
test('server changes after check block retry without adopting its version',async()=>{const h=harness();await assert.rejects(h.c.save());await h.c.recover();h.repo.probe=async()=>({state:'different',saved:null,currentVersion:4});await h.c.recover(true);assert.equal(h.sent.length,1);assert.equal(h.c.record?.document_version,3);assert.equal(h.c.result?.state,'different');});
for(const kind of ['unauthenticated','unavailable','conflict','failed'] as const)test(`${kind} retains attempt and draft through same-actor recovery`,async()=>{const h=harness();h.repo.send=async()=>{throw new ScheduleRepositoryError(kind);};await assert.rejects(h.c.save(),{kind});const a=h.c.attempt;h.c.suspend();h.c.bind(actor);assert.equal(h.c.attempt,a);h.repo.probe=async()=>{throw new ScheduleRepositoryError(kind);};await assert.rejects(h.c.recover(),{kind});assert.equal(h.c.attempt,a);assert.equal(h.dirty(),true);});
test('definite invalid input frees the attempt for corrected draft submission',async()=>{const h=harness();h.repo.send=async()=>{throw new ScheduleRepositoryError('invalid');};await assert.rejects(h.c.save(),{kind:'invalid'});assert.equal(h.c.attempt,null);assert.equal(h.dirty(),true);});
for(const operation of ['send','probe'] as const)test(`account change rejects late ${operation} and clears old attempt`,async()=>{const h=harness(),d=deferred<StoredSchedule|SaveResult>();let pending:Promise<boolean>;if(operation==='send'){h.repo.send=async()=>d.promise as Promise<StoredSchedule>;pending=h.c.save();}else{await assert.rejects(h.c.save());h.repo.probe=async()=>d.promise as Promise<SaveResult>;pending=h.c.recover();}const a=h.c.attempt!;h.c.bind(org);d.resolve(operation==='send'?saved(a):{state:'matched',saved:saved(a),currentVersion:4});assert.equal(await pending,false);assert.equal(h.c.attempt,null);assert.equal(h.c.record,null);assert.equal(h.dirty(),true);});
test('same-actor token transition retains pending attempt and invalidates its late acknowledgement',async()=>{const h=harness(),d=deferred<StoredSchedule>();h.repo.send=async()=>d.promise;const pending=h.c.save(),a=h.c.attempt!;h.c.suspend();h.c.bind(actor);d.resolve(saved(a));assert.equal(await pending,false);assert.equal(h.c.attempt,a);h.repo.probe=async()=>({state:'matched',saved:saved(a),currentVersion:4});await h.c.recover();assert.equal(h.c.attempt,null);});
test('held check suppresses duplicate checks and cannot replace a changed document session',async()=>{const h=harness();await assert.rejects(h.c.save());const a=h.c.attempt!,d=deferred<SaveResult>();h.repo.probe=async()=>d.promise;const p=h.c.recover();assert.equal(await h.c.recover(),false);h.state.documentSession++;d.resolve({state:'matched',saved:saved(a),currentVersion:4});assert.equal(await p,false);assert.equal(h.dirty(),true);assert.equal(h.loads(),0);});
test('unavailable check is not failure proof; successful explicit reload clears recovery',async()=>{const h=harness();await assert.rejects(h.c.save());h.repo.probe=async()=>({state:'unavailable',saved:null,currentVersion:null});await h.c.recover();assert.ok(h.c.attempt);assert.equal(await h.c.recover(true),false);await h.c.open(id);assert.equal(h.c.attempt,null);assert.equal(h.loads(),1);});
test('acknowledgements require exact document, version, author, identity and lifecycle metadata',async()=>{const a=attempt(),valid=saved(a);assert.ok(saveMatches(a,valid));for(const patch of [{id:org},{organization_id:prod},{production_id:day},{production_day_id:id},{updated_by:org},{updated_at:'bad'},{document_version:5},{document_schema_version:2},{document:before.document},{display_name:'Renamed'},{status:'archived'},{deleted_at:'2026-09-16T00:00:00Z'}]){assert.equal(saveMatches(a,{...valid,...patch} as StoredSchedule),false);const h=harness();h.repo.send=async()=>({...valid,...patch} as StoredSchedule);await assert.rejects(h.c.save(),{kind:'failed'});assert.ok(h.c.attempt);assert.equal(h.dirty(),true);}});
test('history match requires the exact next author/document/metadata; missing history never matches',()=>{const a=attempt(),v=history();assert.ok(savedFromHistory(a,v));assert.equal(savedFromHistory(a,null),null);for(const patch of [{schedule_id:org},{organization_id:prod},{production_id:day},{created_by:org},{version:5},{document:before.document},{metadata:null},{metadata:{...v.metadata,slug:'other'}}])assert.equal(savedFromHistory(a,{...v,...patch}),null);});
function sdkHarness(){let currentActor=actor,selectedActor:string|null=actor,token='captured-token',response:StoredSchedule=structuredClone(before),v:ScheduleHistory|null=null,error:{code:string}|null=null,sequence:StoredSchedule[]=[],constraintReceipt=false;const calls:{name:string;args:unknown;steps:unknown[][]}[]=[];
 function query(name:string,args:unknown){const call={name,args,steps:[] as unknown[][]};calls.push(call);const q:Record<string,unknown>={then(resolve:unknown,reject:unknown){return Promise.resolve({data:name==='check_schedule_template_save'?constraintReceipt:name==='schedule_versions'?v:(sequence.shift()??response),error,status:error?.code==='PT401'?401:200}).then(resolve as never,reject as never);}};for(const method of ['select','eq','maybeSingle','setHeader'])q[method]=(...values:unknown[])=>{call.steps.push([method,...values]);return q;};return q;}
 const sdk={auth:{getSession:async()=>({data:{session:{user:{id:currentActor},access_token:token}},error:null})},rpc:query,from:query} as unknown as SupabaseClient;
 return {repo:createSaveRecoveryRepository(sdk,()=>selectedActor),calls,set(value:{constraintReceipt?:boolean;actor?:string;selected?:string|null;token?:string;response?:StoredSchedule;sequence?:StoredSchedule[];history?:ScheduleHistory|null;error?:{code:string}|null}){if('constraintReceipt'in value)constraintReceipt=value.constraintReceipt!;if(value.actor)currentActor=value.actor;if('selected'in value)selectedActor=value.selected!;if(value.token)token=value.token;if(value.response)response=value.response;if(value.sequence)sequence=value.sequence;if('history'in value)v=value.history!;if('error'in value)error=value.error!;}};
}
test('transport pins actor token, exact version/document and scoped history filters',async()=>{const h=sdkHarness(),a=attempt();h.set({response:saved(a)});await h.repo.send(a);assert.deepEqual(h.calls[0].args,{target_schedule_id:id,expected_version:3,next_document:a.document,schema_version:1});h.set({history:history()});assert.equal((await h.repo.probe(a)).state,'matched');for(const call of h.calls)assert.ok(call.steps.some(s=>s[0]==='setHeader'&&s[2]==='Bearer captured-token'));const call=h.calls.find(c=>c.name==='schedule_versions')!;for(const [key,value] of [['organization_id',org],['schedule_id',id],['version',4]])assert.ok(call.steps.some(s=>s[0]==='eq'&&s[1]===key&&s[2]===value));});
test('different SDK or selected account blocks old attempt before any API request',async()=>{for(const patch of [{actor:org},{selected:org},{selected:null}]){const h=sdkHarness();h.set(patch);await assert.rejects(h.repo.send(attempt()),{kind:'unauthenticated'});await assert.rejects(h.repo.probe(attempt()),{kind:'unauthenticated'});assert.equal(h.calls.length,0);}});
test('probe distinguishes baseline, missing history after changed version, matching older history and denial',async()=>{const h=sdkHarness(),a=attempt();assert.equal((await h.repo.probe(a)).state,'retryable');h.set({response:saved(a)});assert.equal((await h.repo.probe(a)).state,'different');h.set({response:{...saved(a),document_version:5},history:history()});const result=await h.repo.probe(a);assert.equal(result.state,'matched');assert.equal(result.saved?.document_version,4);assert.equal(result.currentVersion,5);h.set({error:{code:'PT404'}});assert.deepEqual(await h.repo.probe(a),{state:'unavailable',saved:null,currentVersion:null});h.set({error:{code:'PT401'}});await assert.rejects(h.repo.probe(a),{kind:'unauthenticated'});});
test('same version with changed baseline or malformed acknowledgement does not enable exact retry',async()=>{const h=sdkHarness();h.set({response:{...before,document:{...before.document,meta:{...before.document.meta!,town:'Drift'}}}});assert.equal((await h.repo.probe(attempt())).state,'different');h.set({response:{...saved(),updated_by:org}});await assert.rejects(h.repo.send(attempt()),{kind:'failed'});});

test('matching history cannot clean a contradictory current record at the same version',async()=>{const h=sdkHarness();h.set({response:{...saved(),document:before.document},history:history()});await assert.rejects(h.repo.probe(attempt()),{kind:'failed'});});
test('history advancing beyond the first read requires a fresh matching current read',async()=>{const h=sdkHarness();h.set({sequence:[before,saved()],history:history()});assert.equal((await h.repo.probe(attempt())).state,'matched');assert.equal(h.calls.filter(c=>c.name==='session_read_schedule').length,2);h.set({sequence:[before,before]});await assert.rejects(h.repo.probe(attempt()),{kind:'failed'});});

test('Apply save recovery requires an exact constraint receipt as well as a matching immutable document',async()=>{const h=sdkHarness(),a=captureSaveAttempt({...attempt(),templateUses:[{id:org,version:2,policy:'source-policy'}]});h.set({response:saved(a),history:history(saved(a))});assert.equal((await h.repo.probe(a)).state,'different');h.set({constraintReceipt:true});assert.equal((await h.repo.probe(a)).state,'matched');const probe=h.calls.find(c=>c.name==='check_schedule_template_save')!;assert.deepEqual(probe.args,{target_schedule_id:id,saved_version:4,template_uses:a.templateUses});});
test('Apply save transport sends captured source constraints through the atomic template save endpoint',async()=>{const h=sdkHarness(),a=captureSaveAttempt({...attempt(),templateUses:[{id:org,version:2,policy:'source-policy'}]});h.set({response:saved(a)});await h.repo.send(a);assert.equal(h.calls[0].name,'save_schedule_with_templates');assert.deepEqual((h.calls[0].args as {template_uses:unknown}).template_uses,a.templateUses);});
