import test from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { documentFixture } from '../fixtures/document-fixtures.ts';
import { ScheduleFileImport, validateFileDocument, parseScheduleFile, encodeScheduleFile, documentHash, suggestedSlug, unchangedInventory } from '../../lib/platform/schedule-files.ts';
import { ScheduleRepositoryError, type StoredSchedule } from '../../lib/platform/schedule-repository.ts';
import type { LifecycleAttempt, LifecycleTransport } from '../../lib/platform/schedule-lifecycle-controller.ts';
const actor=randomUUID(),org=randomUUID(),day=randomUUID();
function record(id:string=randomUUID()):StoredSchedule {return {id,organization_id:org,production_id:randomUUID(),production_day_id:day,display_name:'Fictional schedule',slug:'fictional-schedule',status:'draft',deleted_at:null,archived_from_status:null,document_schema_version:1,document_version:1,document:documentFixture(),updated_at:new Date().toISOString(),updated_by:actor};}
function selection(name='Copy'){return {name,slug:suggestedSlug(name),data:documentFixture()};}
function saved(a:LifecycleAttempt){return {...record(a.id),display_name:a.name,slug:a.slug,document:structuredClone(a.document)};}
test('schedule-only JSON preserves complete documents, source provenance and canonical hash',async()=>{const r=record(),file=await encodeScheduleFile([r]);const entries=await parseScheduleFile(JSON.stringify(file),'');assert.deepEqual(entries[0].data,r.document);assert.equal(entries[0].source!.id,r.id);assert.equal(entries[0].sha256,await documentHash(r.document));assert.ok(file.excludes.includes('snapshots'));assert.equal(await documentHash({b:2,a:1}),await documentHash({a:1,b:2}));});
test('legacy formats are accepted without importing any legacy network adapter',async()=>{const d=documentFixture();for(const value of [d,{Legacy:d},{format:'roseland-schedules',version:1,schedules:[{name:'Legacy',data:d}]}])assert.deepEqual((await parseScheduleFile(JSON.stringify(value),'Legacy'))[0].data,d);});
test('tampered hashes, partial entries, invalid JSON and unsupported versions fail closed',async()=>{const file=await encodeScheduleFile([record()]);file.schedules[0].data.rows![0].notes+='tampered';await assert.rejects(parseScheduleFile(JSON.stringify(file),''),/checksum mismatch/);for(const v of ['{','{}','{"format":"production-command-schedule-only","version":2,"schedules":[]}','{"format":"roseland-schedules","version":1,"schedules":[{"name":"Bad"}]}'])await assert.rejects(parseScheduleFile(v,''));});
test('unrecognized fields, bounds, dates, times and large nested collections are rejected without stripping',()=>{const transforms=[(d:any)=>d.extra=1,(d:any)=>d.meta.privateField='x',(d:any)=>d.meta.date='2026-02-31',(d:any)=>d.meta.lat=91,(d:any)=>d.meta.dayNumber=0,(d:any)=>d.rows[0].timeIn='25:00',(d:any)=>d.rows[0].dur='00:80',(d:any)=>d.rows[0].subLocations=Array.from({length:101},()=>({loc:'A'})),(d:any)=>d.rows[0].subLocations[0].extra=1,(d:any)=>d.meta.callsheet.notes='x'.repeat(10001)];for(const f of transforms){const d=documentFixture();f(d);assert.throws(()=>validateFileDocument(d));}});
test('oversize file and count limits reject before review',async()=>{await assert.rejects(parseScheduleFile(' '.repeat(20_000_001),''),/20 MB/);assert.throws(()=>new ScheduleFileImport(actor,org,day,Array.from({length:501},(_,i)=>selection('Copy '+i))),/1–500/);});
test('copy review freezes current draft and never mutates the source or later edits',()=>{const source=selection(),before=structuredClone(source.data),review=new ScheduleFileImport(actor,org,day,[source]);const id=review.items[0].attempt!.id;source.data.rows[0].notes='newer edits';assert.deepEqual(review.items[0].attempt!.document,before);assert.equal(source.data.rows[0].notes,'newer edits');assert.notEqual(id,record().id);assert.ok(Object.isFrozen(review.items[0].attempt!.document));});
test('duplicate names, slugs and generated IDs fail before sending',()=>{assert.throws(()=>new ScheduleFileImport(actor,org,day,[selection('Copy'),{...selection('copy'),slug:'different'}]),/Duplicate/);assert.throws(()=>new ScheduleFileImport(actor,org,day,[selection('A'),{...selection('B'),slug:'a'}]),/Duplicate/);assert.throws(()=>new ScheduleFileImport(actor,org,day,[selection('A'),selection('B')],()=>day),/identity/);});
test('partial failure stops batch; lost acknowledgement recovers same UUID and skips completed items',async()=>{const review=new ScheduleFileImport(actor,org,day,[selection('One'),selection('Two'),selection('Three')]),sent:string[]=[],committed=new Map<string,StoredSchedule>();let lose=true;const transport:LifecycleTransport={async send(a){sent.push(a.id);const r=saved(a);committed.set(a.id,r);if(a.name==='Two'&&lose){lose=false;throw new ScheduleRepositoryError('failed');}return r;},async probe(a){return committed.has(a.id)?{state:'matched',current:committed.get(a.id)!,matchedVersion:1}:{state:'unavailable',current:null,matchedVersion:null};}};await review.execute(transport,()=>true);assert.deepEqual(review.receipt().map(x=>x.state),['success','uncertain','review']);await review.execute(transport,()=>true);assert.equal(review.complete,true);assert.equal(sent.length,3);assert.equal(new Set(sent).size,3);});
test('uncommitted failure retries the exact reviewed ID/document',async()=>{const review=new ScheduleFileImport(actor,org,day,[selection()]);let calls=0;const seen:LifecycleAttempt[]=[];const transport:LifecycleTransport={async send(a){seen.push(a);if(calls++===0)throw new ScheduleRepositoryError('failed');return saved(a);},async probe(){return {state:'unavailable',current:null,matchedVersion:null};}};await review.execute(transport,()=>true);await review.execute(transport,()=>true);assert.equal(review.complete,true);assert.strictEqual(seen[0],seen[1]);});
test('permission denial retains identity and prevents later items; auth recovery can retry',async()=>{const review=new ScheduleFileImport(actor,org,day,[selection('A'),selection('B')]);let denied=true,sends=0;const t:LifecycleTransport={async send(a){sends++;if(denied)throw new ScheduleRepositoryError('unauthenticated');return saved(a);},async probe(){return {state:'unavailable',current:null,matchedVersion:null};}};const id=review.items[0].attempt!.id;await review.execute(t,()=>true);assert.equal(sends,1);assert.equal(review.items[0].failure,'unauthenticated');denied=false;await review.execute(t,()=>true);assert.equal(review.complete,true);assert.equal(review.items[0].attempt!.id,id);});
test('scope change stops later writes and duplicate execution does not send twice',async()=>{const review=new ScheduleFileImport(actor,org,day,[selection('A'),selection('B')]);let release!:(v:StoredSchedule)=>void,active=true,sends=0;const t:LifecycleTransport={async send(a){sends++;return new Promise(r=>release=()=>r(saved(a)));},async probe(){throw new Error('unused');}};const pending=review.execute(t,()=>active);await review.execute(t,()=>active);active=false;release(record());await pending;assert.equal(sends,1);assert.equal(review.items[1].phase,'review');});
test('conflicting identity blocks retry rather than allocating a replacement',async()=>{const review=new ScheduleFileImport(actor,org,day,[selection()]);let sends=0;const t:LifecycleTransport={async send(){sends++;throw new ScheduleRepositoryError('conflict');},async probe(){return {state:'different',current:record(),matchedVersion:null};}};await review.execute(t,()=>true);await review.execute(t,()=>true);assert.equal(sends,1);assert.equal(review.items[0].phase,'conflict');});
test('changed export inventory rejects incomplete or mixed output',()=>{assert.doesNotThrow(()=>unchangedInventory([{id:'1',v:1}],[{v:1,id:'1'}]));assert.throws(()=>unchangedInventory([{id:'1',v:1}],[{id:'1',v:2}]),/changed/);assert.throws(()=>unchangedInventory([{id:'1'}],[]),/changed/);});

test('overwrite instructions are rejected rather than silently discarded',async()=>{const file=await encodeScheduleFile([record()]);await assert.rejects(parseScheduleFile(JSON.stringify({...file,overwrite:true}),''));await assert.rejects(parseScheduleFile(JSON.stringify({...file,schedules:[{...file.schedules[0],targetId:randomUUID()}]}),''));await assert.rejects(parseScheduleFile(JSON.stringify({format:'roseland-schedules',version:1,schedules:[{name:'Overwrite',data:documentFixture(),overwrite:true}]}),''),/create-only/);});

test('production-only import retains its reviewed destination and document through lost acknowledgement',async()=>{
  const placement={productionId:randomUUID(),phaseId:null};
  const entry=selection('Production import'),before=structuredClone(entry.data);
  const review=new ScheduleFileImport(actor,org,null,[entry],undefined,placement);
  const attempt=review.items[0].attempt!;
  placement.productionId=randomUUID();entry.data.rows[0].notes='Later source edit';
  assert.equal(attempt.dayId,null);assert.equal(attempt.productionId,review.placement!.productionId);
  assert.notEqual(attempt.productionId,placement.productionId);assert.deepEqual(attempt.document,before);
  let sent=0;const result={...saved(attempt),production_id:attempt.productionId!,production_day_id:null,phase_id:null};
  const transport:LifecycleTransport={async send(){sent++;throw new ScheduleRepositoryError('failed');},async probe(){return {state:'matched',current:result,matchedVersion:1};}};
  await review.execute(transport,()=>true);assert.equal(review.complete,false);
  await review.execute(transport,()=>true);assert.equal(review.complete,true);assert.equal(sent,1);
  assert.equal(review.receipt()[0].production,attempt.productionId);assert.equal(review.receipt()[0].day,null);
});
