import test from 'node:test';
import assert from 'node:assert/strict';
import type {SupabaseClient} from '@supabase/supabase-js';
import {captureTemplateAttempt,createTemplateRepository,templateReceipt,retainTemplateRequest,readTemplateRequest,clearTemplateRequest,type TemplateAttempt} from '../../lib/platform/schedule-templates.ts';
import {documentFixture} from '../fixtures/document-fixtures.ts';
const actor='11111111-1111-4111-8111-111111111111',org='22222222-2222-4222-8222-222222222222',prod='33333333-3333-4333-8333-333333333333',id='44444444-4444-4444-8444-444444444444',request='55555555-5555-4555-8555-555555555555';
function attempt():TemplateAttempt{return {actor,organization:org,production:prod,id,request,version:0,operation:'create',name:'Fictional template',rows:documentFixture(2).rows,source:request,sourceVersion:1};}
function storage(){const map=new Map<string,string>();return {getItem:(k:string)=>map.get(k)??null,setItem:(k:string,v:string)=>{map.set(k,v);},removeItem:(k:string)=>{map.delete(k);}};}
test('Captured template mutation retains every nested row and exact request identity after newer edits',()=>{const value=attempt(),captured=captureTemplateAttempt(value);value.rows![0].subLocations![0].loc='newer';value.name='newer';assert.equal(captured.name,'Fictional template');assert.notEqual(captured.rows![0].subLocations![0].loc,'newer');assert.ok(Object.isFrozen(captured.rows![0].subLocations));assert.equal(captured.request,request);});
test('Template acknowledgement must match request, object, action and exact next version',()=>{const a=captureTemplateAttempt(attempt()),receipt={request_id:request,id,version:1,operation:'create',confirmed:true};assert.deepEqual(templateReceipt(receipt,a),receipt);for(const patch of [{request_id:id},{id:request},{version:2},{operation:'replace'},{confirmed:false}])assert.throws(()=>templateReceipt({...receipt,...patch},a));});
test('Durable pending request survives reload only under the original account and organization',()=>{const s=storage(),a=captureTemplateAttempt(attempt());retainTemplateRequest(s,{attempt:a,started:true});assert.deepEqual(readTemplateRequest(s,actor,org),{attempt:a,started:true});assert.equal(readTemplateRequest(s,org,org),null);assert.equal(readTemplateRequest(s,actor,actor),null);clearTemplateRequest(s,{...a,request:id});assert.ok(readTemplateRequest(s,actor,org));clearTemplateRequest(s,a);assert.equal(readTemplateRequest(s,actor,org),null);});
test('Failed storage readback prevents dispatch-ready recovery state',()=>{assert.throws(()=>retainTemplateRequest({getItem:()=>null,setItem:()=>{},removeItem:()=>{}},{attempt:attempt(),started:true}),/No new request was sent/);});
function harness(){const calls:{name:string;args:Record<string,unknown>}[]=[];let signed=actor,data:unknown=null;const client={auth:{getSession:async()=>({data:{session:{user:{id:signed},access_token:'fictional-token'}},error:null})},rpc:(name:string,args:Record<string,unknown>)=>{calls.push({name,args});return {setHeader:(key:string,value:string)=>{assert.equal(key,'Authorization');assert.equal(value,'Bearer fictional-token');return Promise.resolve({data,error:null});}};}} as unknown as SupabaseClient;return {repo:createTemplateRepository(client),calls,set:(value:unknown)=>{data=value;},sign:(value:string)=>{signed=value;}};}
test('A changed account cannot send or probe an old template request',async()=>{const h=harness();h.sign(org);await assert.rejects(h.repo.send(attempt()),{kind:'unauthenticated'});await assert.rejects(h.repo.probe(attempt()),{kind:'unauthenticated'});assert.equal(h.calls.length,0);});
test('Publication has a separate server operation and retries use the same reviewed version',async()=>{const h=harness(),a=captureTemplateAttempt({...attempt(),operation:'publish',version:4,rows:null,source:null,sourceVersion:null});h.set({request_id:request,id,version:5,operation:'publish',confirmed:true});await h.repo.send(a);await h.repo.send(a);assert.deepEqual(h.calls[0],h.calls[1]);assert.equal(h.calls[0].name,'publish_schedule_template');assert.equal(h.calls[0].args.publish,true);assert.equal(h.calls[0].args.expected_version,4);h.set({confirmed:false});assert.equal(await h.repo.probe(a),null);});
test('Template reads reject a different organization, target or malformed rows',async()=>{const h=harness(),row={id,organization_id:org,production_id:prod,name:'Fixture',version:1,deleted_at:null,published_at:null,can_manage:true,can_trash:true,can_publish:false,rows:documentFixture(2).rows};for(const patch of [{organization_id:actor},{id:request},{rows:[{unknown:'not removed'}]}]){h.set({...row,...patch});await assert.rejects(h.repo.read(actor,id,org));}h.set({template:row,target_id:request,target_version:1,policy:'policy'});await assert.rejects(h.repo.reviewApply(actor,id,id,org));});

test('Definitive server validation rejection stays distinct from an uncertain transport failure',async()=>{const client={auth:{getSession:async()=>({data:{session:{user:{id:actor},access_token:'fictional-token'}},error:null})},rpc:()=>({setHeader:()=>Promise.resolve({data:null,error:{code:'PT400'},status:400})})} as unknown as SupabaseClient;await assert.rejects(createTemplateRepository(client).send(attempt()),{kind:'invalid'});});
