import test from 'node:test';
import assert from 'node:assert/strict';
import type {SupabaseClient} from '@supabase/supabase-js';
import {captureSnapshotExtra,retainSnapshotExtra,readSnapshotExtra,clearSnapshotExtra,createSnapshotExtras,type SnapshotExtraAttempt} from '../../lib/platform/schedule-snapshot-extras.ts';
const id=(n:number)=>`00000000-0000-4000-8000-${n.toString().padStart(12,'0')}`;
const policy:SnapshotExtraAttempt={kind:'policy',actor:id(1),organization:id(2),request:id(3),version:0,retention:null,trash:'organizer'};
function storage(){const data=new Map<string,string>();return {get length(){return data.size;},key:(i:number)=>[...data.keys()][i]??null,getItem:(k:string)=>data.get(k)??null,setItem:(k:string,v:string)=>{data.set(k,v);},removeItem:(k:string)=>{data.delete(k);}};}
test('snapshot policy validation preserves no-expiry and rejects invalid retention',()=>{const saved=captureSnapshotExtra(policy);assert.equal(saved.kind,'policy');if(saved.kind==='policy')assert.equal(saved.retention,null);for(const retention of [0,-1,1.5,36501,NaN])assert.throws(()=>captureSnapshotExtra({...policy,retention}));assert.ok(Object.isFrozen(captureSnapshotExtra(policy)));});
test('settings and copy journals isolate actor and request, and cannot silently overwrite another tab',()=>{const s=storage();retainSnapshotExtra(s,{attempt:policy,started:true});const next={...policy,request:id(4)};retainSnapshotExtra(s,{attempt:next,started:false});assert.equal(s.length,2);assert.equal(readSnapshotExtra(s,id(5),id(2)),null);clearSnapshotExtra(s,policy);assert.equal(readSnapshotExtra(s,id(1),id(2))?.attempt.request,id(4));});
test('failed durable readback prevents a settings request from being prepared',()=>{assert.throws(()=>retainSnapshotExtra({getItem:()=>null,setItem:()=>{},removeItem:()=>{}},{attempt:policy,started:false}),/No new request/);});
test('copy response must match original request, snapshot, destination identity and version',async()=>{const copy:SnapshotExtraAttempt={kind:'copy',actor:id(1),organization:id(2),request:id(3),schedule:id(4),snapshot:id(5),version:1,id:id(6),sourceVersion:3,policy:'reviewed',production:id(7),day:null,phase:null,name:'Fictional copy',slug:'fictional-copy'};let response={request_id:id(3),id:id(6),snapshot_id:id(5),status:'confirmed',version:1};let signed=id(1);const client={auth:{getSession:async()=>({data:{session:{user:{id:signed},access_token:'fictional'}},error:null})},rpc:()=>({setHeader:()=>Promise.resolve({data:response,error:null})})} as unknown as SupabaseClient;const repo=createSnapshotExtras(client);assert.equal((await repo.send(copy)).id,id(6));response={...response,id:id(9)};await assert.rejects(()=>repo.send(copy));signed=id(9);await assert.rejects(()=>repo.send(copy),/Sign in/);});
