import {readFileSync} from 'node:fs';import {execFileSync} from 'node:child_process';
const f=JSON.parse(readFileSync('/private/tmp/roseland-b11-fixtures.json','utf8'));if(f.project!=='roseland-b08-20260917')throw Error('Fictional fixture required');const origin='http://127.0.0.1:3435';let count=0;function check(v:unknown,m:string){if(!v)throw Error(m);count++;console.log('PASS '+m);}
async function send(body:unknown,from=origin){return fetch(origin+'/api/platform/local-client-view',{method:'POST',headers:{'content-type':'application/json',origin:from},body:JSON.stringify(body),redirect:'error'});}
const r=await send({token:f.liveToken});check(r.ok,'Built endpoint resolves valid scoped bearer');const d=await r.json();check(d.document.rows[0].notes==='Client-visible row note'&&!JSON.stringify(d).includes('HIDDEN-'),'Built response preserves allowlist exclusions');check(r.headers.get('cache-control')?.includes('no-store')&&r.headers.get('referrer-policy')==='no-referrer','Response prevents caching and referrers');
check((await send({token:f.liveToken},'https://untrusted.example')).status===403,'Cross-origin browser request denied');check((await send({token:'bad'})).status===404,'Malformed bearer gets generic unavailable');check((await send({token:'a'.repeat(64)})).status===404,'Guessed bearer gets generic unavailable');
check((await send({token:f.legacyToken,legacyName:f.legacyName})).ok,'Original HMAC legacy link resolves through built server');check((await send({token:f.legacyToken,legacyName:'wrong-name'})).status===404,'Legacy signature cannot be moved to a different name');
const sql=(q:string)=>execFileSync('docker',['exec','-i','supabase_db_'+f.project,'psql','-XqAt','-v','ON_ERROR_STOP=1','-U','postgres','-d','postgres'],{input:q,encoding:'utf8',stdio:['pipe','pipe','pipe']});
const saved=JSON.parse(sql(`select document from public.schedules where id='${f.schedule}';`));
const {createRequire}=await import('node:module');const require=createRequire(import.meta.url);const projection=require('../netlify/lib/public-view.js').publicSchedule;
check(JSON.stringify(d.document)===JSON.stringify(projection(saved))||JSON.stringify(Object.keys(d.document).sort())===JSON.stringify(['meta','rows']), 'Response has only the explicit document sections');
const {isDeepStrictEqual}=await import('node:util');check(isDeepStrictEqual(d.document,projection(saved)),'Database Client projection equals legacy field allowlist exactly');
const {randomUUID}=await import('node:crypto');const restriction=randomUUID();
try{sql(`insert into public.schedule_restrictions(id,organization_id,production_id,schedule_id,subject_user_id,denied_actions,authority,created_by)values('${restriction}','${f.organization}','${f.production}','${f.schedule}','${f.editor.id}',array['export'],'owner','${f.owner.id}');`);check((await send({token:f.liveToken})).status===404,'Current export restriction also blocks external dissemination');}finally{sql(`delete from public.schedule_restrictions where id='${restriction}';`);}
const template=sql(`select id from private.schedule_templates where organization_id='${f.organization}' limit 1;`).trim();if(!template)throw Error('Preserved fictional template required');const binding='b11-'+randomUUID();
try{sql(`insert into private.schedule_template_bindings(schedule_id,template_id,fingerprint,contexts)values('${f.schedule}','${template}','${binding}','[{"production":"${f.production}","membership":false,"restrictions":[{"role":"everyone","actions":["export"]}]}]'::jsonb);`);check((await send({token:f.liveToken})).status===404,'Inherited template source restriction blocks Client output');}finally{sql(`delete from private.schedule_template_bindings where schedule_id='${f.schedule}' and fingerprint='${binding}';`);}
try{sql("update private.client_view_rate set window_at=clock_timestamp(),hits=240 where id;");check((await send({token:f.liveToken})).status===429,'Shared read rate budget returns 429 without a document');}finally{sql('update private.client_view_rate set hits=0 where id;');}
for(const path of ['/local-client','/view','/view/Fictional']){const page=await fetch(origin+path,{redirect:'manual'});check(page.status===200&&page.headers.get('referrer-policy')==='no-referrer'&&page.headers.get('cache-control')?.includes('no-store'),'Read-only route admits anonymous view with no-store headers: '+path);}
check(!readFileSync('/private/tmp/b11-app.log','utf8').includes(f.liveToken)&&!readFileSync('/private/tmp/b11-app.log','utf8').includes(f.legacyToken),'Application log contains neither new nor legacy bearer');
console.log(`PASS ${count} built HTTP sharing assertions.`);
