// B11 focused genuine Auth/SQL acceptance. Fictional unlinked local stack only.
import {execFileSync} from 'node:child_process';
import {readFileSync,writeFileSync,existsSync} from 'node:fs';
import {resolve} from 'node:path';
import {randomUUID,randomBytes,createHmac,createHash} from 'node:crypto';
import {createClient,type SupabaseClient} from '@supabase/supabase-js';
const dir='/private/tmp/roseland-b08-20260917',project='roseland-b08-20260917';
if(existsSync(dir+'/supabase/.temp/project-ref'))throw Error('Unlinked local fixture required');
const config=JSON.parse(execFileSync(resolve('node_modules/.bin/supabase'),['status','--workdir',dir,'--output','json'],{encoding:'utf8',stdio:['ignore','pipe','pipe']}));
if(config.API_URL!=='http://127.0.0.1:56121')throw Error('Owned loopback required');
const options={auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}},admin=createClient(config.API_URL,config.SERVICE_ROLE_KEY,options),client=()=>createClient(config.API_URL,config.ANON_KEY,options);
const preserved=JSON.parse(readFileSync('/private/tmp/roseland-b10-fixtures.json','utf8'));if(preserved.project!==project)throw Error('Preserved fictional fixture required');
function sql(q:string){return execFileSync('docker',['exec','-i','supabase_db_'+project,'psql','-XqAt','-v','ON_ERROR_STOP=1','-U','postgres','-d','postgres'],{input:q,encoding:'utf8',stdio:['pipe','pipe','pipe']}).trim();}
let count=0;function check(v:unknown,m:string):asserts v{if(!v)throw Error(m);count++;console.log('PASS '+m);}
function totp(secret:string){let bits='';for(const c of secret)bits+='ABCDEFGHIJKLMNOPQRSTUVWXYZ234567'.indexOf(c).toString(2).padStart(5,'0');const key=Buffer.from(bits.match(/.{8}/g)!.map(x=>parseInt(x,2))),n=Buffer.alloc(8);n.writeBigUInt64BE(BigInt(Math.floor(Date.now()/30000)));const h=createHmac('sha1',key).update(n).digest(),o=h.at(-1)!&15;return ((h.readUInt32BE(o)&0x7fffffff)%1000000).toString().padStart(6,'0');}
async function rpc(c:SupabaseClient,name:string,args:Record<string,unknown>){const r=await c.rpc(name,args);if(r.error)throw Error(name+': '+r.error.code+' '+r.error.message);return r.data;}
async function identity(label:string){const email=`b11-${label}-${randomUUID()}@example.test`,password='Fictional1!'+randomBytes(18).toString('hex');const r=await admin.auth.admin.createUser({email,password,email_confirm:true,app_metadata:{b08_terms:'fictional-terms-v1',b08_privacy:'fictional-privacy-v1'}});if(!r.data.user||r.error)throw Error('Fixture creation failed');const c=client();if((await c.auth.signInWithPassword({email,password})).error)throw Error('Fixture login failed');return{id:r.data.user.id,email,password,c};}
const owner=client();check(!(await owner.auth.signInWithPassword({email:preserved.owner.email,password:preserved.owner.password})).error,'Owner genuine sign-in');check(!(await owner.auth.mfa.challengeAndVerify({factorId:preserved.owner.factor.id,code:totp(preserved.owner.factor.secret)})).error,'Owner genuine MFA');
const editor=await identity('editor'),organizer=await identity('organizer'),otherEditor=await identity('other-editor'),viewer=await identity('viewer'),outsider=await identity('outsider');
const org=preserved.organization,schedule=randomUUID(),prod=sql(`select production_id from public.schedules where id='${preserved.schedule}';`);
for(const u of [editor,organizer,otherEditor,viewer])sql(`insert into public.organization_memberships(organization_id,user_id,role,status,joined_at) values('${org}','${u.id}','member','active',now());insert into public.production_memberships(organization_id,production_id,user_id,role,status,joined_at)values('${org}','${prod}','${u.id}','${u===organizer?'organizer':u===viewer?'viewer':'editor'}','active',now());`);
const base=await rpc(owner,'read_schedule',{target_schedule_id:preserved.schedule}),document=structuredClone((Array.isArray(base)?base[0]:base).document);
document.meta.town='Fictional Sharing';document.meta.callsheet={hospital:'HIDDEN-CALLSHEET'};document.rows[0]={...document.rows[0],action:'Shoot',desc:'B11 fictional scene',notes:'Client-visible row note',contactName:'HIDDEN-CONTACT',contactEmail:'hidden@example.test',status:'HIDDEN-STATUS'};
await rpc(owner,'create_schedule_in_production',{target_schedule_id:schedule,target_production_id:prod,target_day_id:null,target_phase_id:null,next_display_name:'B11 Fictional '+schedule.slice(0,8),next_slug:'b11-'+schedule,next_document:document,schema_version:1});
const token=randomBytes(32).toString('hex'),hash=createHash('sha256').update(token).digest('hex'),request=randomUUID(),args={target_schedule_id:schedule,request_id:request,token_hash:hash,expected_version:1};
check((await viewer.c.rpc('create_schedule_client_link',args)).status===404,'Viewer cannot create Client link');check((await outsider.c.rpc('create_schedule_client_link',args)).status===404,'Wrong organization cannot issue link');
check((await editor.c.rpc('create_schedule_client_link',{...args,expected_version:2})).status===409,'Stale saved version cannot issue link');
const created=await rpc(editor.c,'create_schedule_client_link',args);check(created.id===request&&!created.revoked,'Editor creates Client link');check(sql(`select extract(epoch from expires_at-created_at)::int from private.schedule_client_links where id='${request}';`)==='2592000','Default expiry exactly 30 days');
check(JSON.stringify(created)===JSON.stringify(await rpc(editor.c,'create_schedule_client_link',args)),'Exact retry retains grant and expiry');
check((await otherEditor.c.rpc('create_schedule_client_link',args)).status===409,'Request ID is actor bound');check((await editor.c.rpc('create_schedule_client_link',{...args,token_hash:'a'.repeat(64)})).status===409,'Changed token conflicts');
const read=()=>rpc(admin,'read_schedule_client_view',{token_hash:hash});let view=await read();check(view?.document.rows[0].notes==='Client-visible row note','Client response preserves ordinary row notes');check(!JSON.stringify(view).includes('HIDDEN-'),'Actual projection omits contacts call sheet and status');check(!('id' in view)&&!('document_version' in view)&&!('history' in view),'Projection omits internal identity version and history');
check((await client().rpc('read_schedule_client_view',{token_hash:hash})).error!==null,'Anonymous role cannot bypass server projection route');check((await editor.c.rpc('read_schedule_client_view',{token_hash:hash})).error!==null,'Authenticated role cannot call service-only resolver');
check(await rpc(admin,'read_schedule_client_view',{token_hash:'0'.repeat(64)})===null,'Guessed token returns no document');
check((await otherEditor.c.rpc('revoke_schedule_client_link',{target_schedule_id:schedule,target_link_id:request,link_kind:'client'})).status===404,'Unrelated Editor cannot revoke another creator link');
let rule=randomUUID();await rpc(owner,'set_schedule_restriction',{target_id:rule,target_organization_id:org,target_production_id:prod,target_schedule_id:schedule,subject_role:null,subject_user_id:editor.id,denied_actions:['share'],expected_revision:0});check(await read()===null,'New leadership sharing restriction invalidates existing reads');check((await editor.c.rpc('create_schedule_client_link',{...args,request_id:randomUUID()})).status===404,'Share restriction also denies issuance');
await rpc(owner,'set_schedule_restriction',{target_id:rule,target_organization_id:org,target_production_id:prod,target_schedule_id:schedule,subject_role:null,subject_user_id:editor.id,denied_actions:[],expected_revision:1});
sql(`update public.production_memberships set role='viewer' where production_id='${prod}' and user_id='${editor.id}';`);check(await read()===null,'Creator role downgrade blocks existing grant');sql(`update public.production_memberships set role='editor' where production_id='${prod}' and user_id='${editor.id}';`);
const lifecycle=await rpc(owner,'read_organization_lifecycle',{target_organization_id:org});await rpc(owner,'request_organization_deletion',{target_organization_id:org,request_id:randomUUID(),expected_version:lifecycle.version,confirmed:true});check(!!(await read()),'Existing scoped Client read survives pending organization deletion');check((await editor.c.rpc('create_schedule_client_link',{...args,request_id:randomUUID()})).status===423,'Frozen organization denies link creation');check((await organizer.c.rpc('revoke_schedule_client_link',{target_schedule_id:schedule,target_link_id:request,link_kind:'client'})).status===423,'Frozen organization denies ordinary link mutation');await rpc(owner,'cancel_organization_deletion',{target_organization_id:org,request_id:randomUUID(),expected_version:lifecycle.version+1});
await rpc(organizer.c,'revoke_schedule_client_link',{target_schedule_id:schedule,target_link_id:request,link_kind:'client'});check(await read()===null,'Authorized Organizer revokes link');check((await rpc(organizer.c,'revoke_schedule_client_link',{target_schedule_id:schedule,target_link_id:request,link_kind:'client'})).revoked,'Revocation retry is idempotent');check((await rpc(editor.c,'create_schedule_client_link',args)).revoked,'Old issuance retry cannot revive revoked link');
const liveToken=randomBytes(32).toString('hex'),liveHash=createHash('sha256').update(liveToken).digest('hex'),liveId=randomUUID();await rpc(editor.c,'create_schedule_client_link',{...args,request_id:liveId,token_hash:liveHash});
sql(`update private.schedule_client_links set created_at=created_at-interval '31 days',expires_at=expires_at-interval '31 days' where id='${liveId}';`);check(await rpc(admin,'read_schedule_client_view',{token_hash:liveHash})===null,'Expired token denied');sql(`update private.schedule_client_links set created_at=created_at+interval '31 days',expires_at=expires_at+interval '31 days' where id='${liveId}';`);
const legacyName='Fictional legacy B11 '+schedule,alias=randomUUID(),legacySecret=randomBytes(32).toString('hex'),legacyExpires=Math.floor(Date.now()/1000)+86400,legacyToken=legacyExpires+'.'+createHmac('sha256',legacySecret).update(`schedule-view:v2:${legacyName}:${legacyExpires}`).digest('hex');
sql(`insert into private.schedule_client_aliases(id,legacy_name,organization_id,schedule_id,creator_id)values('${alias}','${legacyName}','${org}','${schedule}','${editor.id}');`);
check(!!await rpc(admin,'read_schedule_client_view',{token_hash:null,legacy_name:legacyName,legacy_expires:legacyExpires}),'Trusted original-expiry legacy alias resolves stable schedule');
check(await rpc(admin,'read_schedule_client_view',{token_hash:null,legacy_name:legacyName,legacy_expires:Math.floor(Date.now()/1000)-1})===null,'Legacy alias does not extend original expiry');
check((await rpc(editor.c,'list_schedule_client_links',{target_schedule_id:schedule})).links.length===3,'Creator sees own grants and legacy alias without raw secrets');
check(!sql(`select row_to_json(l) from private.schedule_client_links l where id='${liveId}';`).includes(liveToken),'Database stores only token digest');
const clean=(u:typeof editor)=>({id:u.id,email:u.email,password:u.password});writeFileSync('/private/tmp/roseland-b11-fixtures.json',JSON.stringify({project,organization:org,production:prod,schedule,owner:preserved.owner,editor:clean(editor),organizer:clean(organizer),otherEditor:clean(otherEditor),viewer:clean(viewer),outsider:clean(outsider),liveToken,liveId,legacyName,alias,legacySecret,legacyToken},null,2),{mode:0o600});
console.log(`PASS ${count} focused B11 Auth/SQL assertions; private fictional fixture saved.`);
