import{randomUUID,randomBytes,createHash}from'node:crypto';import{readFileSync,writeFileSync}from'node:fs';import{isDeepStrictEqual}from'node:util';import{client,admin,config,project,sql,q,totp}from'./b13-local.ts';
const checks:string[]=[];function check(v:unknown,label:string){if(!v)throw Error(label);checks.push(label);console.log('PASS '+label);}
async function identity(name:string){const email=`b13-${name}-${randomUUID()}@example.test`,password='Fictional1!'+randomBytes(20).toString('hex');const r=await admin.auth.admin.createUser({email,password,email_confirm:true,app_metadata:{b08_terms:'fictional-terms-v1',b08_privacy:'fictional-privacy-v1'}});if(r.error||!r.data.user)throw Error('Fixture creation failed');const c=client();if((await c.auth.signInWithPassword({email,password})).error)throw Error('Fixture sign-in failed');return{id:r.data.user.id,email,password,c};}
async function rpc(c:any,name:string,args:any={}){const r=await c.rpc(name,args);if(r.error)throw Error(name+': '+r.error.message);return r.data;}
const owner=await identity('owner'),editor=await identity('editor'),viewer=await identity('viewer'),outsider=await identity('outsider'),organization=randomUUID(),otherOrg=randomUUID(),production=randomUUID(),otherProduction=randomUUID(),schedule=randomUUID(),otherSchedule=randomUUID(),template=randomUUID(),snapshot=randomUUID();
const receipts=JSON.parse(readFileSync('evidence/b12-integration/synthetic-checkpoints.json','utf8'));const entry=receipts[1].capture.entries.find((e:any)=>e.store==='schedules'&&e.key==='alpha-new');const document=JSON.parse(Buffer.from(entry.bytes,'base64').toString());document.meta.town='B13 fictional source';document.rows[0].notes='B13 client note';document.rows[0].contactName='B13 PRIVATE CONTACT';
sql(`begin;insert into public.organizations(id,name,slug)values('${organization}','B13 Fictional Studio','b13-${organization}'),('${otherOrg}','B13 Other Studio','b13-${otherOrg}');insert into public.organization_memberships(organization_id,user_id,role,status,joined_at)values('${organization}','${owner.id}','owner','active',now()),('${organization}','${editor.id}','member','active',now()),('${organization}','${viewer.id}','member','active',now()),('${otherOrg}','${outsider.id}','owner','active',now());insert into public.productions(id,organization_id,name,slug)values('${production}','${organization}','B13 production','b13'),('${otherProduction}','${otherOrg}','Other production','other');insert into public.production_memberships(organization_id,production_id,user_id,role,status,joined_at)values('${organization}','${production}','${editor.id}','editor','active',now()),('${organization}','${production}','${viewer.id}','viewer','active',now());insert into public.schedules(id,organization_id,production_id,display_name,slug,document,created_by,updated_by)values('${schedule}','${organization}','${production}','B13 Fictional','b13',${q(JSON.stringify(document))},'${owner.id}','${owner.id}');commit;`);
check((await owner.c.rpc('read_schedule',{target_schedule_id:schedule})).error!==null,'Owner AAL1 denied before genuine enrollment');
const enrollment=await owner.c.auth.mfa.enroll({factorType:'totp',friendlyName:'B13 fictional'});if(enrollment.error||!enrollment.data)throw Error('Enrollment failed');const factor={id:enrollment.data.id,secret:enrollment.data.totp.secret};if((await owner.c.auth.mfa.challengeAndVerify({factorId:factor.id,code:totp(factor.secret)})).error)throw Error('MFA failed');
check(isDeepStrictEqual((await rpc(owner.c,'read_schedule',{target_schedule_id:schedule})).document,document),'Genuine MFA owner reads complete B12-derived document');
for(const u of [owner,editor,viewer])check((await u.c.from('schedules').select('id').eq('id',schedule)).data?.length===1,'Direct REST scoped read '+u.email.split('-')[1]);
check((await outsider.c.from('schedules').select('id').eq('id',schedule)).data?.length===0,'Other organization direct REST does not disclose schedule');
check((await viewer.c.rpc('update_schedule_document',{target_schedule_id:schedule,expected_version:1,next_document:document,schema_version:1})).error!==null,'Viewer cannot mutate through write RPC');
const malformed=structuredClone(document);malformed.rows[0].unknown='discard must not happen';check((await editor.c.rpc('update_schedule_document',{target_schedule_id:schedule,expected_version:1,next_document:malformed,schema_version:1})).error!==null,'Unknown nested field refused without stripping');
await rpc(owner.c,'save_organization_presentation',{target_organization_id:organization,request_id:randomUUID(),expected_version:0,next_config:{labels:{hdrTitle:'Fictional B13'}}});check((await editor.c.rpc('save_organization_presentation',{target_organization_id:organization,request_id:randomUUID(),expected_version:1,next_config:{labels:{hdrTitle:'Denied'}}})).error!==null,'Editor cannot write organization presentation');
for(const next_config of [{colors:{'--pink':'url(javascript:alert(1))'}},{logo:'javascript:alert(1)'},{labels:{unknown:'x'}},{actionStyles:{aShoot:{bg:'#000000;display:none',text:'#ffffff'}}}])check((await owner.c.rpc('save_organization_presentation',{target_organization_id:organization,request_id:randomUUID(),expected_version:1,next_config})).error!==null,'Malicious/unknown CMS input refused '+Object.keys(next_config)[0]);
sql(`insert into private.schedule_templates(id,organization_id,production_id,name,rows,created_by,updated_by)values('${template}','${organization}','${production}','B13 source template',${q(JSON.stringify(document.rows))},'${owner.id}','${owner.id}');insert into private.schedule_template_sources(template_id,organization_id,schedule_id)values('${template}','${organization}','${schedule}');insert into private.schedule_snapshots(id,organization_id,schedule_id,name,kind,document)values('${snapshot}','${organization}','${schedule}','B13 snapshot','named',${q(JSON.stringify(document))});`);
check((await rpc(editor.c,'read_schedule_template',{target_template_id:template})).published_at===null,'Template remains production scoped');check((await outsider.c.rpc('read_schedule_template',{target_template_id:template})).error!==null,'Template outsider denied');check((await outsider.c.rpc('read_schedule_snapshot',{target_snapshot_id:snapshot})).error!==null,'Snapshot outsider denied');
const liveToken=randomBytes(32).toString('hex'),liveId=randomUUID(),hash=createHash('sha256').update(liveToken).digest('hex');await rpc(editor.c,'create_schedule_client_link',{target_schedule_id:schedule,request_id:liveId,token_hash:hash,expected_version:1});
const projected=await rpc(admin,'read_schedule_client_view',{token_hash:hash});check(projected.document.rows[0].notes==='B13 client note'&&!JSON.stringify(projected).includes('B13 PRIVATE'),'Client projection preserves notes and excludes contacts');check((await viewer.c.rpc('read_schedule_client_view',{token_hash:hash})).error!==null,'Ordinary user cannot call trusted Client resolver');
const rule=randomUUID();await rpc(owner.c,'set_schedule_restriction',{target_id:rule,target_organization_id:organization,target_production_id:production,target_schedule_id:schedule,subject_role:null,subject_user_id:editor.id,denied_actions:['export'],expected_revision:0});check(await rpc(admin,'read_schedule_client_view',{token_hash:hash})===null,'Current source export restriction blocks existing Client link');check((await editor.c.rpc('read_schedule_template',{target_template_id:template})).error!==null,'Source export restriction also blocks derived template');await rpc(owner.c,'set_schedule_restriction',{target_id:rule,target_organization_id:organization,target_production_id:production,target_schedule_id:schedule,subject_role:null,subject_user_id:editor.id,denied_actions:[],expected_revision:1});
const frozen=await rpc(owner.c,'request_organization_deletion',{target_organization_id:organization,request_id:randomUUID(),expected_version:0,confirmed:true});check(!!await rpc(admin,'read_schedule_client_view',{token_hash:hash}),'Frozen organization retains permitted scoped Client read');check((await editor.c.rpc('create_schedule_client_link',{target_schedule_id:schedule,request_id:randomUUID(),token_hash:'a'.repeat(64),expected_version:1})).status===423,'Frozen organization rejects share mutation');check([403,404,423].includes((await editor.c.rpc('update_schedule_document',{target_schedule_id:schedule,expected_version:1,next_document:document,schema_version:1})).status),'Frozen organization rejects schedule write');check(!!(await admin.from('schedules').update({display_name:'Denied'}).eq('id',schedule)).error,'Service role cannot bypass organization freeze');await rpc(owner.c,'cancel_organization_deletion',{target_organization_id:organization,request_id:randomUUID(),expected_version:frozen.version});
check(isDeepStrictEqual((await rpc(owner.c,'read_schedule',{target_schedule_id:schedule})).document,document),'Frozen attempts left saved document unchanged');await rpc(editor.c,'revoke_schedule_client_link',{target_schedule_id:schedule,target_link_id:liveId,link_kind:'client'});check(await rpc(admin,'read_schedule_client_view',{token_hash:hash})===null,'Revoked link stays unavailable');const currentToken=randomBytes(32).toString('hex'),currentId=randomUUID();await rpc(editor.c,'create_schedule_client_link',{target_schedule_id:schedule,request_id:currentId,token_hash:createHash('sha256').update(currentToken).digest('hex'),expected_version:1});
const token=(await editor.c.auth.getSession()).data.session!.access_token;
for(const path of ['/storage/v1/bucket','/realtime/v1/api/tenants','/functions/v1/anything']){const r=await fetch(config.API_URL+path,{headers:{apikey:config.ANON_KEY,authorization:'Bearer '+token}});check(!r.ok,'Unused service unavailable '+path);}
const graphql=await fetch(config.API_URL+'/graphql/v1',{method:'POST',headers:{apikey:config.ANON_KEY,authorization:'Bearer '+(await outsider.c.auth.getSession()).data.session!.access_token,'content-type':'application/json'},body:JSON.stringify({query:'{ schedulesCollection { edges { node { id } } } }'})});const graph=await graphql.json();check(graph.errors?.some((e:any)=>e.message==='pg_graphql extension is not enabled.'),'GraphQL extension unavailable; no GraphQL isolation acceptance');
const revokedSession=(await viewer.c.auth.getSession()).data.session!;await viewer.c.auth.signOut();const denied=await fetch(config.API_URL+'/rest/v1/schedules?select=id',{headers:{apikey:config.ANON_KEY,authorization:'Bearer '+revokedSession.access_token}});check(denied.status===401,'Revoked genuine session denied on subsequent Data API call');
const clean=(u:typeof owner)=>({id:u.id,email:u.email,password:u.password});writeFileSync('/private/tmp/roseland-b13-fixtures.json',JSON.stringify({project,organization,otherOrg,production,otherProduction,schedule,template,snapshot,document,owner:{...clean(owner),factor},editor:clean(editor),viewer:clean(viewer),outsider:clean(outsider),liveToken:currentToken,liveId:currentId,revokedToken:liveToken,revokedId:liveId},null,2),{mode:0o600});writeFileSync('evidence/b13-review/composition.json',JSON.stringify({checks,applicationClaims:'genuine Auth and MFA; no forged JWT acceptance',providerRaceInvestigation:false,fixtureStoredPrivately:true},null,2)+'\n');console.log('PASS '+checks.length+' B13 composition checks');
