// B12 genuine Auth/MFA application readback on the owned test API only.
import {execFileSync} from 'node:child_process';import {readFileSync,writeFileSync,existsSync} from 'node:fs';import {resolve} from 'node:path';import {createHmac} from 'node:crypto';import {isDeepStrictEqual} from 'node:util';import {createClient} from '@supabase/supabase-js';
const stack='/private/tmp/roseland-b08-20260917';if(existsSync(stack+'/supabase/.temp/project-ref'))throw Error('Unlinked test stack required');
const cfg=JSON.parse(execFileSync(resolve('node_modules/.bin/supabase'),['status','--workdir',stack,'--output','json'],{encoding:'utf8',stdio:['ignore','pipe','pipe']}));if(cfg.API_URL!=='http://127.0.0.1:56121')throw Error('Test loopback required');
const f=JSON.parse(readFileSync('/private/tmp/roseland-b11-fixtures.json','utf8'));const opts={auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}};const c=createClient(cfg.API_URL,cfg.ANON_KEY,opts);
function totp(secret:string){let bits='';for(const x of secret)bits+='ABCDEFGHIJKLMNOPQRSTUVWXYZ234567'.indexOf(x).toString(2).padStart(5,'0');const key=Buffer.from(bits.match(/.{8}/g)!.map(x=>parseInt(x,2))),b=Buffer.alloc(8);b.writeBigUInt64BE(BigInt(Math.floor(Date.now()/30000)));const h=createHmac('sha1',key).update(b).digest(),o=h.at(-1)!&15;return((h.readUInt32BE(o)&0x7fffffff)%1000000).toString().padStart(6,'0');}
if((await c.auth.signInWithPassword({email:f.owner.email,password:f.owner.password})).error)throw Error('Genuine login failed');if((await c.auth.mfa.challengeAndVerify({factorId:f.owner.factor.id,code:totp(f.owner.factor.secret)})).error)throw Error('Genuine MFA failed');
if(process.argv.includes('--prepare')){const token=(await c.auth.getSession()).data.session!.access_token;writeFileSync('/private/tmp/roseland-b12-auth-claims.json',Buffer.from(token.split('.')[1],'base64url'),{mode:0o600});console.log('Genuine importer actor MFA session prepared; no credentials printed.');process.exit(0);}
const current=JSON.parse(readFileSync('/private/tmp/roseland-b12-current.json','utf8')),root=current.root,p=JSON.parse(readFileSync(root+'/latest-plan.json','utf8')),state=JSON.parse(readFileSync(root+'/final-state.json','utf8')),report=JSON.parse(readFileSync(root+'/report.json','utf8'));let checks:string[]=[];
function check(v:unknown,label:string){if(!v)throw Error(label);checks.push(label);console.log('PASS '+label);}
async function rpc(name:string,args:Record<string,unknown>){const r=await c.rpc(name,args);if(r.error)throw Error(name+': '+r.error.message);return r.data;}
for(const s of p.schedules){const r=await rpc('read_schedule',{target_schedule_id:s.id});check(isDeepStrictEqual(r.document,s.document),'Schedule document '+s.key);check(r.document_version===state['public.schedules'].find((x:any)=>x.id===s.id).document_version,'Schedule version '+s.key);}
const library=await rpc('list_schedule_library',{target_organization_id:p.org});check(library.length===p.schedules.length,'Library exact inventory');for(const s of p.schedules){const r=library.find((x:any)=>x.id===s.id);check(r.display_name===s.name&&r.library_position===s.position&&r.status===s.status&&r.production_id===s.production_id&&r.phase_id===s.phase_id,'Library rename/order/archive/placement '+s.key);}
for(const t of p.templates){const r=await rpc('read_schedule_template',{target_template_id:t.id});check(isDeepStrictEqual(r.rows,t.rows)&&r.name===t.name&&r.published_at===null,'Production template '+t.name);}
for(const production of p.productions){const r=await rpc('list_schedule_templates',{target_production_id:production.id});check(r.length===p.templates.filter((t:any)=>t.production_id===production.id).length,'Template exact inventory');}
for(const s of p.schedules){const listed=await rpc('list_schedule_snapshots',{target_schedule_id:s.id});check(listed.length===state['private.schedule_snapshots'].filter((x:any)=>x.schedule_id===s.id).length,'Snapshots exact inventory '+s.key);}
for(const s of state['private.schedule_snapshots']){const r=await rpc('read_schedule_snapshot',{target_snapshot_id:s.id});check(isDeepStrictEqual(r.document,s.document)&&r.original_id===s.original_id&&r.original_order===s.original_order,'Snapshot readback '+s.original_id);}
const presentation=await rpc('read_organization_presentation',{target_organization_id:p.org});check(isDeepStrictEqual(presentation.config,p.presentation),'CMS exact readback');
const service=createClient(cfg.API_URL,cfg.SERVICE_ROLE_KEY,opts);
for(const a of p.aliases){const r=await service.rpc('read_schedule_client_view',{token_hash:null,legacy_name:a.name,legacy_expires:Math.floor(Date.now()/1000)+600});if(r.error)throw r.error;const s=p.schedules.find((s:any)=>s.id===a.schedule_id);check(r.data.document.meta.town===s.document.meta.town&&r.data.document.rows[0].notes===s.document.rows[0].notes,'Client alias resolves latest stable identity '+a.id);check(!JSON.stringify(r.data).includes('contactName'),'Client alias excludes private contact');}
const outsider=createClient(cfg.API_URL,cfg.ANON_KEY,opts);if((await outsider.auth.signInWithPassword({email:f.outsider.email,password:f.outsider.password})).error)throw Error('Outsider sign-in failed');check((await outsider.rpc('read_schedule',{target_schedule_id:p.schedules[0].id})).error!==null,'Other organization cannot read imported schedule');check((await outsider.rpc('read_schedule_template',{target_template_id:p.templates[0].id})).error!==null,'Other organization cannot read imported template');check((await outsider.rpc('read_schedule_snapshot',{target_snapshot_id:state['private.schedule_snapshots'][0].id})).error!==null,'Other organization cannot read imported snapshot');
report.application_readback=true;report.application_checks=checks;report.application_evidence='Genuine password login + MFA, current application RPCs; service-only alias projection readback. No simulated JWT used for API acceptance.';writeFileSync(root+'/report.json',JSON.stringify(report,null,2)+'\n');console.log('PASS '+checks.length+' genuine application checks.');
