import{readFileSync,writeFileSync}from'node:fs';import{execFileSync}from'node:child_process';import{createHash}from'node:crypto';import{client,config,sql}from'./b13-local.ts';
const f=JSON.parse(readFileSync('/private/tmp/roseland-b13-fixtures.json','utf8'));
const checks:string[]=[];function check(v:unknown,s:string){if(!v)throw Error(s);checks.push(s);console.log('PASS '+s);}
const editor=client(),outsider=client();for(const [c,u]of [[editor,f.editor],[outsider,f.outsider]]as const){if((await c.auth.signInWithPassword(u)).error)throw Error('Local login failed');}
const graph=async(c:any)=>{const r=await fetch(config.API_URL+'/graphql/v1',{method:'POST',headers:{apikey:config.ANON_KEY,authorization:'Bearer '+(await c.auth.getSession()).data.session.access_token,'content-type':'application/json'},body:JSON.stringify({query:'{ schedulesCollection { edges { node { id } } } }'})});return{status:r.status,body:await r.json()};};
const own=await graph(editor),other=await graph(outsider);check([own,other].every(r=>r.status===200&&r.body.errors?.some((e:any)=>e.message==='pg_graphql extension is not enabled.')),'GraphQL explicitly unavailable in this local stack; tenant filtering not claimed');
const paths=execFileSync('git',['ls-files','--cached','--others','--exclude-standard','-z'],{encoding:'utf8'}).split('\0').filter(Boolean);const secrets=[config.SERVICE_ROLE_KEY,f.owner.password,f.editor.password,f.owner.factor.secret,f.liveToken,f.revokedToken];for(const p of paths){const s=readFileSync(p).toString();if(secrets.some(x=>s.includes(x)))throw Error('Private fixture material found in candidate: '+p);}check(true,'Candidate tracked and untracked files exclude exact configured service key and private fixture material');
const hook=sql(`select setconfig::text from pg_db_role_setting where setrole=(select oid from pg_roles where rolname='authenticator')`);check(hook.includes('pgrst.db_pre_request=public.check_application_session'),'Actual PostgREST role installs current session admission hook');
const hash=(p:string)=>createHash('sha256').update(readFileSync(p)).digest('hex');const pins={buildId:readFileSync('.next/BUILD_ID','utf8').trim(),configSha256:hash('/private/tmp/roseland-b13-source/supabase/config.toml'),lockSha256:hash('package-lock.json'),migrationHistorySha256:createHash('sha256').update(sql('select json_agg(x order by version) from supabase_migrations.schema_migrations x')).digest('hex')};writeFileSync('evidence/b13-review/supplement.json',JSON.stringify({checks,graphQL:{ownStatus:own.status,foreignStatus:other.status},pins,secretScanScope:'Exact known local fixture secrets in candidate files; not a full entropy scanner or historical repository audit.'},null,2)+'\n');
