import{readFileSync,writeFileSync,readdirSync,statSync}from'node:fs';import{join}from'node:path';import{config,client,totp}from'./b13-local.ts';
const f=JSON.parse(readFileSync('/private/tmp/roseland-b13-fixtures.json','utf8')),origin='http://127.0.0.1:3455',checks:string[]=[];
function check(v:unknown,s:string){if(!v)throw Error(s);checks.push(s);console.log('PASS '+s);}
const paths=['/api/platform/invitations','/api/platform/invitations/'+f.schedule+'/revoke','/api/platform/organizations','/api/platform/local-membership-notifications','/api/platform/local-organization-notifications'];
const bodies=[{organizationId:f.organization,email:'nobody@example.test'},{reason:'Fictional review'},{ownerUserId:f.owner.id,name:'Fictional',slug:'fictional',reason:'Fictional review'},{organizationId:f.organization,eventId:f.schedule},{organizationId:f.organization,eventId:f.schedule,recipientId:f.owner.id}];
for(const [i,path] of paths.entries()){const r=await fetch(origin+path,{method:'POST',headers:{'content-type':'application/json',origin,'idempotency-key':'b13-'+crypto.randomUUID()},body:JSON.stringify(bodies[i])});check(r.status===401,'Missing bearer denied '+path);check(r.headers.get('cache-control')?.includes('no-store'),'Private response cache denied '+path);const cross=await fetch(origin+path,{method:'POST',headers:{'content-type':'application/json',origin:'https://outside.invalid','idempotency-key':'b13-'+crypto.randomUUID()},body:JSON.stringify(bodies[i])});check(cross.status===403,'Foreign origin denied '+path);}
const places=await fetch(origin+'/api/places',{method:'POST',headers:{cookie:'rp_auth_flag=1','content-type':'application/json'},body:JSON.stringify({input:'fictional'})});check(places.status===401,'Built Places route rejects forged UI flag without provider call');
for(const body of [{token:'bad'},{token:'0'.repeat(64)},{token:f.revokedToken}]){const r=await fetch(origin+'/api/platform/local-client-view',{method:'POST',headers:{'content-type':'application/json',origin},body:JSON.stringify(body)});check(r.status===404,'Malformed/guessed/revoked Client bearer hidden');}
const shared=await fetch(origin+'/api/platform/local-client-view',{method:'POST',headers:{'content-type':'application/json',origin},body:JSON.stringify({token:f.liveToken})});const view=await shared.json();check(shared.ok&&view.document.rows[0].notes==='B13 client note'&&!JSON.stringify(view).includes('B13 PRIVATE'),'Built Client allowlist survives current composition');check(shared.headers.get('cache-control')?.includes('no-store')&&shared.headers.get('referrer-policy')==='no-referrer','Built Client cache/referrer protections');
for(const path of ['/local-client','/view','/view/Fictional']){const r=await fetch(origin+path,{redirect:'manual'});check(r.status===200&&r.headers.get('x-frame-options')==='DENY'&&r.headers.get('referrer-policy')==='no-referrer','Public view response boundary '+path);}
const mail=await fetch(origin+'/api/platform/local-account/mail',{method:'POST',headers:{'content-type':'application/json',origin:'https://outside.invalid'},body:'{}'});check(mail.status===403,'Cross-origin mail request denied before provider');
const owner=client();if((await owner.auth.signInWithPassword(f.owner)).error)throw Error('Owner sign-in failed');if((await owner.auth.mfa.challengeAndVerify({factorId:f.owner.factor.id,code:totp(f.owner.factor.secret)})).error)throw Error('Owner MFA failed');const bearer=(await owner.auth.getSession()).data.session!.access_token;
const wrong=await fetch(origin+'/api/platform/invitations',{method:'POST',headers:{origin,'content-type':'application/json',authorization:'Bearer '+bearer,'idempotency-key':'b13-'+crypto.randomUUID(),'x-actor-user-id':f.outsider.id,'x-actor-aal':'aal2'},body:JSON.stringify({organizationId:f.otherOrg,email:'recipient@example.test',organizationRole:'member',expiresInDays:7})});check([403,404].includes(wrong.status),'Forged actor header cannot cross organization through privileged server route');
function files(path:string):string[]{return readdirSync(path).flatMap(n=>{const p=join(path,n);return statSync(p).isDirectory()?files(p):[p];});}
for(const path of files('.next/static')){const text=readFileSync(path).toString();for(const secret of [config.SERVICE_ROLE_KEY,f.owner.password,f.owner.factor.secret,f.liveToken])if(text.includes(secret))throw Error('Secret in client bundle');}check(true,'Actual client bundle contains no configured service key or fictional private access material');
const log=readFileSync('/private/tmp/b13-app.log','utf8');check(!log.includes(f.liveToken)&&!log.includes(f.revokedToken)&&!log.includes(bearer)&&!log.includes(config.SERVICE_ROLE_KEY),'Built application log excludes tested secrets');writeFileSync('evidence/b13-review/http.json',JSON.stringify({checks,realProviderCalls:0},null,2)+'\n');console.log('PASS '+checks.length+' B13 built HTTP checks');
