const test=require('node:test');
const assert=require('node:assert/strict');
const {sourceLoader}=require('./source-loader.cjs');
function setup(count=32){const load=sourceLoader();const store=load('lib/store/scheduleStore.ts').useScheduleStore;const fixture=load('tests/fixtures/document-fixtures.ts').documentFixture(count);store.getState().loadSchedule('Fictional document',fixture);return {store,fixture};}
test('long document fields survive real store load, edits, undo/redo, serialization and reload',()=>{const {store,fixture}=setup();assert.deepEqual(store.getState().meta,fixture.meta);fixture.rows.forEach((r,i)=>{const actual=store.getState().rows[i];for(const key of Object.keys(r).filter(k=>k!=='timeIn'))assert.deepEqual(actual[key],r[key],`${i}.${key}`);});const old=store.getState().getScheduleData();store.getState().pushUndo();const cs={...old.meta.callsheet,notes:'  Preserved whitespace\n"quoted", ending  ',basecamp:'Edited fictional basecamp'};store.getState().updateMeta({callsheet:cs});store.getState().undo();assert.deepEqual(store.getState().meta.callsheet,old.meta.callsheet);store.getState().redo();assert.deepEqual(store.getState().meta.callsheet,cs);const saved=JSON.parse(JSON.stringify(store.getState().getScheduleData()));store.getState().loadSchedule('Reload',saved);assert.deepEqual(store.getState().getScheduleData().rows,saved.rows);assert.deepEqual(store.getState().meta,saved.meta);assert.equal(store.getState().dirty,false);});
test('refresh/clear of sun rows retains ordinary row identities, nested content and zero duration',()=>{const {store}=setup(3);const original=structuredClone(store.getState().rows),keys=[...store.getState().rowKeys];for(let i=0;i<3;i++)store.getState().insertSunRows('6:30 AM','7:15 PM');assert.equal(store.getState().rows.filter(r=>r.sunLocked).length,2);assert.deepEqual(store.getState().rows.filter(r=>!r.sunLocked),original);assert.deepEqual(store.getState().rowKeys.filter((_,i)=>!store.getState().rows[i].sunLocked),keys);store.getState().clearSunRows();assert.deepEqual(store.getState().rows,original);assert.deepEqual(store.getState().rowKeys,keys);assert.equal(store.getState().rows[0].dur,'00:00');});
test('weather metadata and sun changes undo as one user operation without changing call sheet',()=>{const {store}=setup(3);const original=store.getState().getScheduleData();store.getState().pushUndo();store.getState().setWx({sunrise:'5:45 AM',sunset:'8:00 PM',noForecast:true});store.getState().insertSunRows('5:45 AM','8:00 PM');store.getState().undo();assert.deepEqual(store.getState().rows,original.rows);assert.deepEqual(store.getState().meta,original.meta);store.getState().redo();assert.equal(store.getState().meta.wx.noForecast,true);assert.deepEqual(store.getState().meta.callsheet,original.meta.callsheet);});

test('sunrise precedes sunset when both markers share the insertion point before a late call',()=>{const {store}=setup(1);store.getState().updateRow(0,{timeIn:'11:45 PM',dur:'00:30'});store.getState().insertSunRows('7:00 AM','7:15 PM');assert.deepEqual(store.getState().rows.filter(r=>r.sunLocked).map(r=>r.action),['🌅 Sunrise','🌇 Sunset']);assert.equal(store.getState().rows.find(r=>!r.sunLocked).timeIn,'11:45 PM');});
