const test=require('node:test');
const assert=require('node:assert/strict');
const {sourceLoader}=require('./source-loader.cjs');
function setup(){const load=sourceLoader(),store=load('lib/store/scheduleStore.ts').useScheduleStore,fixture=load('tests/fixtures/document-fixtures.ts').documentFixture;store.getState().loadSchedule('Receiving schedule',fixture(4));return {store,fixture};}
const use={id:'11111111-1111-4111-8111-111111111111',version:2,policy:'fictional-policy'};
test('Apply preserves all receiving metadata, document identity and unsaved status with independent row keys',()=>{const {store,fixture}=setup(),before=structuredClone(store.getState().getScheduleData()),session=store.getState().documentSession,keys=[...store.getState().rowKeys],rows=fixture(2).rows;store.getState().applyTemplateRows(rows,use);assert.deepEqual(store.getState().meta,before.meta);assert.equal(store.getState().scheduleName,'Receiving schedule');assert.equal(store.getState().documentSession,session);assert.equal(store.getState().dirty,true);assert.equal(store.getState().rows.length,2);assert.equal(store.getState().rowKeys.length,2);assert.ok(store.getState().rowKeys.every(k=>!keys.includes(k)));rows[0].subLocations[0].loc='Changed outside store';assert.notEqual(store.getState().rows[0].subLocations[0].loc,'Changed outside store');assert.deepEqual(store.getState().templateUses,[use]);assert.equal('templateUses' in store.getState().getScheduleData(),false);});
test('Undo and redo preserve row count, nested content and the matching Apply provenance',()=>{const {store,fixture}=setup(),before=structuredClone(store.getState().getScheduleData());store.getState().applyTemplateRows(fixture(2).rows,use);const after=structuredClone(store.getState().rows);store.getState().undo();assert.deepEqual(store.getState().rows,before.rows);assert.deepEqual(store.getState().meta,before.meta);assert.equal(store.getState().rowKeys.length,4);assert.deepEqual(store.getState().templateUses,[]);store.getState().redo();assert.deepEqual(store.getState().rows,after);assert.equal(store.getState().rowKeys.length,2);assert.deepEqual(store.getState().templateUses,[use]);});
test('Confirming an earlier Apply save removes only acknowledged uses from current, undo and redo drafts',()=>{const {store,fixture}=setup(),second={...use,id:'22222222-2222-4222-8222-222222222222'};store.getState().applyTemplateRows(fixture(2).rows,use);store.getState().applyTemplateRows(fixture(3).rows,second);store.getState().acknowledgeTemplateUses([use]);assert.deepEqual(store.getState().templateUses,[second]);assert.equal(store.getState().dirty,true);store.getState().undo();assert.deepEqual(store.getState().templateUses,[]);store.getState().redo();assert.deepEqual(store.getState().templateUses,[second]);store.getState().loadSchedule('Other',fixture(1));assert.deepEqual(store.getState().templateUses,[]);});

test('Applying a newer review replaces obsolete pending provenance while Undo restores the exact earlier draft',()=>{const {store,fixture}=setup(),newer={...use,version:3,policy:'changed-policy'};store.getState().applyTemplateRows(fixture(2).rows,use);store.getState().applyTemplateRows(fixture(3).rows,newer);assert.deepEqual(store.getState().templateUses,[newer]);store.getState().undo();assert.deepEqual(store.getState().templateUses,[use]);assert.equal(store.getState().rows.length,2);});
